"""board toolset — GENERATED by scripts/gen_toolsets.py, do not hand-edit.

Source of truth: tests/fixtures/tools_baseline.json (module "board").
"""

from __future__ import annotations

from typing import Annotated, Any, Dict, List, Literal, Optional, Union

from pydantic import BaseModel, Field

from kicad_mcp.toolsets._common import dispatch_command

class AddBoardOutlineParamsPointsItem(BaseModel):
    x: Annotated[float, Field(description="X coordinate")]
    y: Annotated[float, Field(description="Y coordinate")]


class AddBoardOutlineParams(BaseModel):
    """Parameters for the outline shape"""

    width: Annotated[Optional[float], Field(description="Width of rectangle")] = None
    height: Annotated[Optional[float], Field(description="Height of rectangle")] = None
    cornerRadius: Annotated[Optional[float], Field(description="Corner radius for rounded_rectangle (mm)")] = None
    radius: Annotated[Optional[float], Field(description="Radius of circle")] = None
    points: Annotated[Optional[List[AddBoardOutlineParamsPointsItem]], Field(description="Points of polygon")] = None
    x: Annotated[float, Field(description="X coordinate of top-left corner for rectangles (default: 0)")]
    y: Annotated[float, Field(description="Y coordinate of top-left corner for rectangles (default: 0)")]
    unit: Annotated[Literal["mm", "mil", "inch"], Field(description="Unit of measurement")]


class AddBoardTextPosition(BaseModel):
    """Position of the text"""

    x: Annotated[float, Field(description="X coordinate")]
    y: Annotated[float, Field(description="Y coordinate")]
    unit: Annotated[Literal["mm", "mil", "inch"], Field(description="Unit of measurement")]


class AddMountingHolePosition(BaseModel):
    """Position of the mounting hole"""

    x: Annotated[float, Field(description="X coordinate")]
    y: Annotated[float, Field(description="Y coordinate")]
    unit: Annotated[Literal["mm", "mil", "inch"], Field(description="Unit of measurement")]


class AddZonePointsItem(BaseModel):
    x: Annotated[float, Field(description="X coordinate")]
    y: Annotated[float, Field(description="Y coordinate")]

def add_board_outline(
    shape: Annotated[Literal["rectangle", "circle", "polygon", "rounded_rectangle"], Field(description="Shape of the outline")],
    params: Annotated[AddBoardOutlineParams, Field(description="Parameters for the outline shape")],
) -> dict[str, Any]:
    """Draw the PCB board outline (Edge.Cuts layer) as a rectangle, rounded rectangle, circle or polygon."""
    return dispatch_command("add_board_outline", {"shape": shape, "params": params})


def add_board_text(
    text: Annotated[str, Field(description="Text content")],
    position: Annotated[AddBoardTextPosition, Field(description="Position of the text")],
    layer: Annotated[str, Field(description="Layer to place the text on")],
    size: Annotated[float, Field(description="Text size")],
    thickness: Annotated[Optional[float], Field(description="Line thickness")] = None,
    rotation: Annotated[Optional[float], Field(description="Rotation angle in degrees")] = None,
    style: Annotated[Optional[Literal["normal", "italic", "bold"]], Field(description="Text style")] = None,
) -> dict[str, Any]:
    """Add a text label to a PCB layer (e.g. silkscreen, fab, courtyard)."""
    return dispatch_command("add_board_text", {"text": text, "position": position, "layer": layer, "size": size, "thickness": thickness, "rotation": rotation, "style": style})


def add_layer(
    name: Annotated[str, Field(description="Layer name")],
    type: Annotated[Literal["copper", "technical", "user", "signal"], Field(description="Layer type")],
    position: Annotated[Literal["top", "bottom", "inner"], Field(description="Layer position")],
    number: Annotated[Optional[float], Field(description="Layer number (for inner layers)")] = None,
) -> dict[str, Any]:
    """Add a new copper or technical layer to the PCB stackup."""
    return dispatch_command("add_layer", {"name": name, "type": type, "position": position, "number": number})


def add_mounting_hole(
    position: Annotated[AddMountingHolePosition, Field(description="Position of the mounting hole")],
    diameter: Annotated[float, Field(description="Diameter of the hole")],
    padDiameter: Annotated[Optional[float], Field(description="Optional diameter of the pad around the hole")] = None,
) -> dict[str, Any]:
    """Place a mounting hole (NPTH or PTH) at the specified position on the PCB."""
    return dispatch_command("add_mounting_hole", {"position": position, "diameter": diameter, "padDiameter": padDiameter})


def add_zone(
    layer: Annotated[str, Field(description="Layer for the zone")],
    net: Annotated[str, Field(description="Net name for the zone")],
    points: Annotated[List[AddZonePointsItem], Field(description="Points defining the zone outline")],
    unit: Annotated[Literal["mm", "mil", "inch"], Field(description="Unit of measurement")],
    clearance: Annotated[Optional[float], Field(description="Clearance value")] = None,
    minWidth: Annotated[Optional[float], Field(description="Minimum width")] = None,
    padConnection: Annotated[Optional[Literal["thermal", "solid", "none"]], Field(description="Pad connection type")] = None,
) -> dict[str, Any]:
    """Create a copper fill zone (pour) on a PCB layer for a specified net."""
    return dispatch_command("add_zone", {"layer": layer, "net": net, "points": points, "unit": unit, "clearance": clearance, "minWidth": minWidth, "padConnection": padConnection})


def get_board_2d_view(
    pcbPath: Annotated[Optional[str], Field(description="Absolute path to the .kicad_pcb file. Falls back to the currently loaded board if omitted.")] = None,
    layers: Annotated[Optional[List[str]], Field(description="Layer names to include, e.g. [\"F.Cu\",\"B.Cu\",\"Edge.Cuts\"]. Omit for all layers.")] = None,
    width: Annotated[Optional[float], Field(description="Output image width in pixels (default: 1600)")] = None,
    height: Annotated[Optional[float], Field(description="Output image height in pixels (default: 1200)")] = None,
    format: Annotated[Optional[Literal["png", "jpg", "svg"]], Field(description="Output format (default: png)")] = None,
    responseMode: Annotated[Optional[Literal["inline", "file"]], Field(description="\"inline\" (default): image returned directly; \"file\": written to disk, filePath returned")] = None,
) -> dict[str, Any]:
    """Render a 2D image of the PCB using kicad-cli. Returns PNG, JPG, or SVG. Use layers to filter — e.g. ["F.Cu","B.Cu","Edge.Cuts"] for copper + outline only. Use responseMode to choose delivery:   "inline" (default) — PNG/JPG rendered as an image visible to Claude; SVG returned as text.   "file" — image written next to the .kicad_pcb as <board>_2d_view.<ext>; filePath is returned. Use file mode for large boards to avoid MCP message-size limits."""
    return dispatch_command("get_board_2d_view", {"pcbPath": pcbPath, "layers": layers, "width": width, "height": height, "format": format, "responseMode": responseMode})


def get_board_extents(
    unit: Annotated[Optional[Literal["mm", "mil", "inch"]], Field(description="Unit of measurement for the result")] = None,
) -> dict[str, Any]:
    """Return the bounding box (min/max X and Y) of all objects on the current PCB board."""
    return dispatch_command("get_board_extents", {"unit": unit})


def get_board_info() -> dict[str, Any]:
    """Retrieve general information about the current PCB board (dimensions, layer count, DRC status)."""
    return dispatch_command("get_board_info", {})


def get_layer_list() -> dict[str, Any]:
    """Return the list of all layers defined in the current PCB board."""
    return dispatch_command("get_layer_list", {})


def import_svg_logo(
    pcbPath: Annotated[str, Field(description="Path to the .kicad_pcb file")],
    svgPath: Annotated[str, Field(description="Path to the SVG logo file")],
    x: Annotated[float, Field(description="X position of the logo top-left corner in mm")],
    y: Annotated[float, Field(description="Y position of the logo top-left corner in mm")],
    width: Annotated[float, Field(description="Target width of the logo in mm (height is scaled to preserve aspect ratio)")],
    layer: Annotated[Optional[str], Field(description="PCB layer name, e.g. F.SilkS or B.SilkS (default: F.SilkS)")] = None,
    strokeWidth: Annotated[Optional[float], Field(description="Outline stroke width in mm (0 = no outline, default 0)")] = None,
    filled: Annotated[Optional[bool], Field(description="Fill polygons with solid colour (default true)")] = None,
) -> dict[str, Any]:
    """Imports an SVG file as filled graphic polygons onto a KiCAD PCB layer (default F.SilkS / front silkscreen). Curves are linearised automatically. Ideal for placing a company or project logo on the board."""
    return dispatch_command("import_svg_logo", {"pcbPath": pcbPath, "svgPath": svgPath, "x": x, "y": y, "width": width, "layer": layer, "strokeWidth": strokeWidth, "filled": filled})


def set_active_layer(
    layer: Annotated[str, Field(description="Layer name to set as active")],
) -> dict[str, Any]:
    """Set the currently active PCB layer by name (e.g. F.Cu, B.Cu)."""
    return dispatch_command("set_active_layer", {"layer": layer})


def set_board_size(
    width: Annotated[float, Field(description="Board width")],
    height: Annotated[float, Field(description="Board height")],
    unit: Annotated[Literal["mm", "mil", "inch"], Field(description="Unit of measurement")],
) -> dict[str, Any]:
    """Set the PCB board dimensions (width and height) in the specified unit."""
    return dispatch_command("set_board_size", {"width": width, "height": height, "unit": unit})


_TOOLS = [
    add_board_outline,
    add_board_text,
    add_layer,
    add_mounting_hole,
    add_zone,
    get_board_2d_view,
    get_board_extents,
    get_board_info,
    get_layer_list,
    import_svg_logo,
    set_active_layer,
    set_board_size,
]


def register(mcp: Any) -> None:
    for fn in _TOOLS:
        mcp.tool()(fn)
