"""component toolset — GENERATED by scripts/gen_toolsets.py, do not hand-edit.

Source of truth: tests/fixtures/tools_baseline.json (module "component").
"""

from __future__ import annotations

from typing import Annotated, Any, Dict, List, Literal, Optional, Union

from pydantic import BaseModel, Field

from kicad_mcp.toolsets._common import dispatch_command

class CheckCourtyardOverlapsBoardOutline(BaseModel):
    """Optional board outline bbox override. Default: derived from Edge.Cuts."""

    x1: float
    y1: float
    x2: float
    y2: float
    unit: Optional[Literal["mm", "inch"]] = None


class DuplicateComponentOffset(BaseModel):
    """Offset from original position"""

    x: float
    y: float
    unit: Optional[Literal["mm", "inch", "mil"]] = None


class GetComponentListBoundingbox(BaseModel):
    """Filter by bounding box region"""

    x1: float
    y1: float
    x2: float
    y2: float
    unit: Optional[Literal["mm", "inch", "mil"]] = None


class MoveComponentPosition(BaseModel):
    """New position coordinates and unit"""

    x: Annotated[float, Field(description="X coordinate")]
    y: Annotated[float, Field(description="Y coordinate")]
    unit: Annotated[Literal["mm", "inch", "mil"], Field(description="Unit of measurement")]


class PlaceComponentPosition(BaseModel):
    """Position coordinates and unit"""

    x: Annotated[float, Field(description="X coordinate")]
    y: Annotated[float, Field(description="Y coordinate")]
    unit: Annotated[Literal["mm", "inch", "mil"], Field(description="Unit of measurement")]


class PlaceComponentArrayStartposition(BaseModel):
    """Starting position"""

    x: float
    y: float
    unit: Literal["mm", "inch", "mil"]


class SuggestPlacementBounds(BaseModel):
    """SCOPED REGROUP: confine movable parts to this box (mm) — e.g. the area beside one IC. Combine with `refs` (that IC's passives) to regroup one cluster at a time; unlisted parts stay as anchors. Far more reliable than a whole-board run on a dense board. Default: whole board."""

    x1: float
    y1: float
    x2: float
    y2: float
    unit: Optional[Literal["mm", "mil", "inch"]] = None


class SuggestPlacementBoardOutline(BaseModel):
    """Optional board containment bbox override. Default: derived from Edge.Cuts."""

    x1: float
    y1: float
    x2: float
    y2: float
    unit: Optional[Literal["mm", "mil", "inch"]] = None

def add_component_annotation(
    reference: Annotated[str, Field(description="Reference designator of the component (e.g., 'R5')")],
    annotation: Annotated[str, Field(description="Annotation or comment text to add")],
    visible: Annotated[Optional[bool], Field(description="Whether the annotation should be visible on the PCB")] = None,
) -> dict[str, Any]:
    """Add a text annotation or comment to a PCB component."""
    return dispatch_command("add_component_annotation", {"reference": reference, "annotation": annotation, "visible": visible})


def align_components(
    references: Annotated[List[str], Field(description="Array of component references to align")],
    alignmentType: Annotated[Literal["horizontal", "vertical", "grid"], Field(description="Type of alignment")],
    spacing: Annotated[Optional[float], Field(description="Spacing between components in mm")] = None,
    referenceComponent: Annotated[Optional[str], Field(description="Reference component for alignment")] = None,
) -> dict[str, Any]:
    """Align multiple PCB components horizontally, vertically or on a grid with optional spacing."""
    return dispatch_command("align_components", {"references": references, "alignmentType": alignmentType, "spacing": spacing, "referenceComponent": referenceComponent})


def check_courtyard_overlaps(
    positions: Annotated[Optional[Dict[str, Any]], Field(description="Virtual placements: map of reference designator to [x, y] or [x, y, rotation_degrees] in mm. Each listed ref is checked AS IF it were at the given coordinates. Unspecified refs use their current board position.")] = None,
    refs: Annotated[Optional[List[str]], Field(description="Limit the check to these refs (default: every footprint on the board).")] = None,
    margin: Annotated[Optional[float], Field(description="Extra clearance in mm added around every courtyard (default 0). Useful to enforce a manufacturing keepout wider than the symbol's declared courtyard.")] = None,
    include_boundary: Annotated[Optional[bool], Field(description="Also flag courtyards that extend past the board outline (default true).")] = None,
    board_outline: Annotated[Optional[CheckCourtyardOverlapsBoardOutline], Field(description="Optional board outline bbox override. Default: derived from Edge.Cuts.")] = None,
) -> dict[str, Any]:
    """Detect courtyard overlaps between footprints and (optionally) flag courtyards that extend past the board outline. Accepts a `positions` dict of hypothetical placements so an AI can validate a proposed move_component / place_component before committing it. Returns overlap pairs with intersection extents (mm) and per-component boundary violations."""
    return dispatch_command("check_courtyard_overlaps", {"positions": positions, "refs": refs, "margin": margin, "include_boundary": include_boundary, "board_outline": board_outline})


def delete_component(
    reference: Annotated[str, Field(description="Reference designator of the component to delete (e.g., 'R5')")],
) -> dict[str, Any]:
    """Remove a component from the PCB by its reference designator."""
    return dispatch_command("delete_component", {"reference": reference})


def duplicate_component(
    reference: Annotated[str, Field(description="Reference of component to duplicate")],
    offset: Annotated[DuplicateComponentOffset, Field(description="Offset from original position")],
    newReference: Annotated[Optional[str], Field(description="New reference designator")] = None,
    count: Annotated[Optional[float], Field(description="Number of duplicates (default: 1)")] = None,
) -> dict[str, Any]:
    """Duplicate an existing PCB component at an offset position, optionally with a new reference designator."""
    return dispatch_command("duplicate_component", {"reference": reference, "offset": offset, "newReference": newReference, "count": count})


def edit_component(
    reference: Annotated[str, Field(description="Reference designator of the component (e.g., 'R5')")],
    newReference: Annotated[Optional[str], Field(description="Optional new reference designator")] = None,
    value: Annotated[Optional[str], Field(description="Optional new component value")] = None,
    footprint: Annotated[Optional[str], Field(description="Optional new footprint")] = None,
) -> dict[str, Any]:
    """Edit properties of an existing PCB component (reference, value, footprint)."""
    return dispatch_command("edit_component", {"reference": reference, "newReference": newReference, "value": value, "footprint": footprint})


def find_component(
    reference: Annotated[Optional[str], Field(description="Reference designator to search for")] = None,
    value: Annotated[Optional[str], Field(description="Component value to search for")] = None,
) -> dict[str, Any]:
    """Search for a PCB component by reference designator or value and return its position and properties."""
    return dispatch_command("find_component", {"reference": reference, "value": value})


def get_component_list(
    layer: Annotated[Optional[str], Field(description="Filter by layer (e.g., 'F.Cu', 'B.Cu')")] = None,
    boundingBox: Annotated[Optional[GetComponentListBoundingbox], Field(description="Filter by bounding box region")] = None,
    unit: Annotated[Optional[Literal["mm", "mil", "inch"]], Field(description="Unit for coordinates (default: mm)")] = None,
) -> dict[str, Any]:
    """Return a list of all components on the PCB, optionally filtered by layer or bounding box region."""
    return dispatch_command("get_component_list", {"layer": layer, "boundingBox": boundingBox, "unit": unit})


def get_component_pads(
    reference: Annotated[str, Field(description="Reference designator of the component (e.g., 'U1')")],
    unit: Annotated[Optional[Literal["mm", "mil", "inch"]], Field(description="Unit for coordinates (default: mm)")] = None,
) -> dict[str, Any]:
    """Return all pads of a PCB component with their positions, net assignments and sizes."""
    return dispatch_command("get_component_pads", {"reference": reference, "unit": unit})


def get_component_properties(
    reference: Annotated[str, Field(description="Reference designator of the component (e.g., 'R5')")],
) -> dict[str, Any]:
    """Return all properties of a PCB component (position, rotation, layer, value, footprint)."""
    return dispatch_command("get_component_properties", {"reference": reference})


def get_pad_position(
    reference: Annotated[str, Field(description="Component reference designator (e.g., 'U1')")],
    pad: Annotated[str, Field(description="Pad number or name (e.g., '1', 'A1')")],
    unit: Annotated[Optional[Literal["mm", "mil", "inch"]], Field(description="Unit for coordinates (default: mm)")] = None,
) -> dict[str, Any]:
    """Return the exact XY position of a specific pad on a PCB component. Use this before routing to get accurate start/end coordinates."""
    return dispatch_command("get_pad_position", {"reference": reference, "pad": pad, "unit": unit})


def group_components(
    references: Annotated[List[str], Field(description="Reference designators of components to group")],
    groupName: Annotated[str, Field(description="Name for the component group")],
) -> dict[str, Any]:
    """Group multiple PCB components together by name for easier selection and manipulation."""
    return dispatch_command("group_components", {"references": references, "groupName": groupName})


def move_component(
    reference: Annotated[str, Field(description="Reference designator of the component (e.g., 'R5')")],
    position: Annotated[MoveComponentPosition, Field(description="New position coordinates and unit")],
    rotation: Annotated[Optional[float], Field(description="Optional new rotation in degrees")] = None,
    layer: Annotated[Optional[str], Field(description="Optional target layer (e.g., 'F.Cu', 'B.Cu') - flips component if needed")] = None,
) -> dict[str, Any]:
    """Move a PCB component to a new position. Optionally update rotation or flip to a different copper layer."""
    return dispatch_command("move_component", {"reference": reference, "position": position, "rotation": rotation, "layer": layer})


def place_component(
    componentId: Annotated[str, Field(description="Identifier for the component to place (e.g., 'R_0603_10k')")],
    position: Annotated[PlaceComponentPosition, Field(description="Position coordinates and unit")],
    reference: Annotated[Optional[str], Field(description="Optional desired reference (e.g., 'R5')")] = None,
    value: Annotated[Optional[str], Field(description="Optional component value (e.g., '10k')")] = None,
    footprint: Annotated[Optional[str], Field(description="Optional specific footprint name")] = None,
    rotation: Annotated[Optional[float], Field(description="Optional rotation in degrees")] = None,
    layer: Annotated[Optional[str], Field(description="Optional layer (e.g., 'F.Cu', 'B.SilkS')")] = None,
    boardPath: Annotated[Optional[str], Field(description="Path to the .kicad_pcb file \u2013 required when using project-local footprint libraries")] = None,
) -> dict[str, Any]:
    """Place a footprint component onto the PCB at the specified position. Optionally set reference, value, footprint, rotation and layer."""
    return dispatch_command("place_component", {"componentId": componentId, "position": position, "reference": reference, "value": value, "footprint": footprint, "rotation": rotation, "layer": layer, "boardPath": boardPath})


def place_component_array(
    componentId: Annotated[str, Field(description="Component identifier")],
    startPosition: Annotated[PlaceComponentArrayStartposition, Field(description="Starting position")],
    rows: Annotated[float, Field(description="Number of rows")],
    columns: Annotated[float, Field(description="Number of columns")],
    rowSpacing: Annotated[float, Field(description="Spacing between rows")],
    columnSpacing: Annotated[float, Field(description="Spacing between columns")],
    startReference: Annotated[Optional[str], Field(description="Starting reference (e.g., 'R1')")] = None,
    footprint: Annotated[Optional[str], Field(description="Footprint name")] = None,
    value: Annotated[Optional[str], Field(description="Component value")] = None,
    rotation: Annotated[Optional[float], Field(description="Rotation in degrees")] = None,
) -> dict[str, Any]:
    """Place a rectangular grid array of identical components on the PCB with configurable row/column spacing."""
    return dispatch_command("place_component_array", {"componentId": componentId, "startPosition": startPosition, "rows": rows, "columns": columns, "rowSpacing": rowSpacing, "columnSpacing": columnSpacing, "startReference": startReference, "footprint": footprint, "value": value, "rotation": rotation})


def replace_component(
    reference: Annotated[str, Field(description="Reference designator of the component to replace")],
    newComponentId: Annotated[str, Field(description="ID of the new component to use")],
    newFootprint: Annotated[Optional[str], Field(description="Optional new footprint")] = None,
    newValue: Annotated[Optional[str], Field(description="Optional new component value")] = None,
) -> dict[str, Any]:
    """Replace an existing PCB component with a different component type, optionally changing footprint and value."""
    return dispatch_command("replace_component", {"reference": reference, "newComponentId": newComponentId, "newFootprint": newFootprint, "newValue": newValue})


def rotate_component(
    reference: Annotated[str, Field(description="Reference designator of the component (e.g., 'R5')")],
    angle: Annotated[float, Field(description="Rotation angle in degrees (absolute, not relative)")],
) -> dict[str, Any]:
    """Rotate a PCB component to an absolute angle in degrees."""
    return dispatch_command("rotate_component", {"reference": reference, "angle": angle})


def set_footprint_type(
    reference: Annotated[str, Field(description="Reference designator of the footprint (e.g. 'R1', 'U3')")],
    type: Annotated[Literal["smd", "through_hole", "unspecified"], Field(description="Placement type: 'smd' for surface-mount, 'through_hole' for PTH components, 'unspecified' to clear both bits (e.g. for board-only or mechanically-placed items)")],
    exclude_from_pos_files: Annotated[Optional[bool], Field(description="When true, suppress this footprint from pick-and-place (.pos) exports. Omit to leave the current setting unchanged.")] = None,
    exclude_from_bom: Annotated[Optional[bool], Field(description="When true, suppress this footprint from BoM exports. Omit to leave the current setting unchanged.")] = None,
    not_in_schematic: Annotated[Optional[bool], Field(description="When true, marks the footprint as board-only (no corresponding schematic symbol). Omit to leave the current setting unchanged.")] = None,
) -> dict[str, Any]:
    """Set the placement type (through_hole / smd / unspecified) and optional exclusion flags on a placed PCB footprint. The placement type controls whether the footprint is included in pick-and-place (.pos) output files. Use exclude_from_pos_files to suppress a footprint from .pos exports without changing its type."""
    return dispatch_command("set_footprint_type", {"reference": reference, "type": type, "exclude_from_pos_files": exclude_from_pos_files, "exclude_from_bom": exclude_from_bom, "not_in_schematic": not_in_schematic})


def suggest_placement(
    refs: Annotated[Optional[List[str]], Field(description="References to move (default: every non-locked footprint on the board).")] = None,
    locked: Annotated[Optional[List[str]], Field(description="References to hold fixed as anchors (connectors, mounting-constrained, RF, edge parts). They still pull movable parts. KiCad-locked footprints are added automatically.")] = None,
    apply: Annotated[Optional[bool], Field(description="If true, move + rotate components to the proposed positions. Default false (dry run \u2014 board untouched).")] = None,
    iterations: Annotated[Optional[float], Field(description="Force-directed relaxation passes (default 200).")] = None,
    grid_mm: Annotated[Optional[float], Field(description="Snap proposed positions to this grid (default 0.5).")] = None,
    margin_mm: Annotated[Optional[float], Field(description="Extra keepout enforced between courtyards (default 0.3).")] = None,
    rotate: Annotated[Optional[bool], Field(description="Enable pin-facing rotation (default true).")] = None,
    spread: Annotated[Optional[bool], Field(description="Enable density spreading (default true). Diffuses parts across free board area so a whole-board run stays legal (few/zero courtyard overlaps) instead of over-packing into a blob. Leave on for whole-board runs.")] = None,
    align: Annotated[Optional[bool], Field(description="Tidy the result into rows/columns (default true). Snaps near-collinear part centers onto shared row (Y) and column (X) lines so passives line up cleanly with centers aligned \u2014 like KiCad's Align Centers + Distribute. Disable for a pure shortest-wire layout.")] = None,
    align_tol_mm: Annotated[Optional[float], Field(description="Max center spacing (mm) for parts to be pulled onto the same row/column line during align (default 1.5).")] = None,
    rotation_steps: Annotated[Optional[List[float]], Field(description="Candidate orientations in degrees (default [0, 90, 180, 270]).")] = None,
    power_nets: Annotated[Optional[List[str]], Field(description="Net-name fragments treated as high-current and pulled short & direct (case-insensitive). Defaults to common rails (VBAT, VBUS, VCC, 3V3, 5V, ...). Pass [] to disable.")] = None,
    power_weight: Annotated[Optional[float], Field(description="Pull multiplier for power nets (default 3.0).")] = None,
    decoupling_boost: Annotated[Optional[float], Field(description="Extra pull for 2-pin-passive <-> multi-pin-IC links so caps/feedback parts hug their IC (default 2.0).")] = None,
    bounds: Annotated[Optional[SuggestPlacementBounds], Field(description="SCOPED REGROUP: confine movable parts to this box (mm) \u2014 e.g. the area beside one IC. Combine with `refs` (that IC's passives) to regroup one cluster at a time; unlisted parts stay as anchors. Far more reliable than a whole-board run on a dense board. Default: whole board.")] = None,
    board_outline: Annotated[Optional[SuggestPlacementBoardOutline], Field(description="Optional board containment bbox override. Default: derived from Edge.Cuts.")] = None,
) -> dict[str, Any]:
    """Propose an optimized PCB footprint placement that shortens net length, orients parts toward their partners, and removes courtyard overlaps. Force-directed clustering pulls connected parts together (a converter's feedback divider and decoupling caps end up hugging its IC), power/high-current nets are weighted short & direct, and each part is rotated (0/90/180/270) to face neighbours so airwires stop crossing. PCB ONLY — does not touch the schematic. DRY RUN by default: returns proposals {ref:[x,y,rot]} plus a score (HPWL before/after, overlap counts) without modifying the board. Validate via check_courtyard_overlaps(positions=proposals), then re-run with apply=true before autoroute."""
    return dispatch_command("suggest_placement", {"refs": refs, "locked": locked, "apply": apply, "iterations": iterations, "grid_mm": grid_mm, "margin_mm": margin_mm, "rotate": rotate, "spread": spread, "align": align, "align_tol_mm": align_tol_mm, "rotation_steps": rotation_steps, "power_nets": power_nets, "power_weight": power_weight, "decoupling_boost": decoupling_boost, "bounds": bounds, "board_outline": board_outline})


_TOOLS = [
    add_component_annotation,
    align_components,
    check_courtyard_overlaps,
    delete_component,
    duplicate_component,
    edit_component,
    find_component,
    get_component_list,
    get_component_pads,
    get_component_properties,
    get_pad_position,
    group_components,
    move_component,
    place_component,
    place_component_array,
    replace_component,
    rotate_component,
    set_footprint_type,
    suggest_placement,
]


def register(mcp: Any) -> None:
    for fn in _TOOLS:
        mcp.tool()(fn)
