"""datasheet toolset — GENERATED by scripts/gen_toolsets.py, do not hand-edit.

Source of truth: tests/fixtures/tools_baseline.json (module "datasheet").
"""

from __future__ import annotations

from typing import Annotated, Any, Dict, List, Literal, Optional, Union

from pydantic import BaseModel, Field

from kicad_mcp.toolsets._common import dispatch_command

def enrich_datasheets(
    schematic_path: Annotated[str, Field(description="Path to the .kicad_sch file to enrich")],
    dry_run: Annotated[bool, Field(description="If true, show what would be changed without writing to disk (default: false)")] = False,
) -> dict[str, Any]:
    """Fill in missing Datasheet URLs in a KiCAD schematic using LCSC part numbers.

For every placed symbol that has:
  • (property "LCSC" "C123456") set
  • (property "Datasheet" "~") or empty

Sets the Datasheet field to:
  https://www.lcsc.com/datasheet/C123456.pdf

The URL is then visible in KiCAD's footprint browser, symbol properties dialog,
and any tool that reads the standard KiCAD Datasheet field.
No API key or internet lookup required – the URL is constructed directly.

Use dry_run=true to preview changes without writing."""
    return dispatch_command("enrich_datasheets", {"schematic_path": schematic_path, "dry_run": dry_run})


def get_datasheet_url(
    lcsc: Annotated[str, Field(description="LCSC part number, with or without \"C\" prefix (e.g. \"C179739\" or \"179739\")")],
) -> dict[str, Any]:
    """Get the LCSC datasheet URL for a component by LCSC number.

Returns the direct PDF URL and product page URL.
No network request – URL is constructed from the LCSC number alone.

Example: get_datasheet_url("C179739")
→ https://www.lcsc.com/datasheet/C179739.pdf"""
    return dispatch_command("get_datasheet_url", {"lcsc": lcsc})


_TOOLS = [
    enrich_datasheets,
    get_datasheet_url,
]


def register(mcp: Any) -> None:
    for fn in _TOOLS:
        mcp.tool()(fn)
