"""design-rules toolset — GENERATED by scripts/gen_toolsets.py, do not hand-edit.

Source of truth: tests/fixtures/tools_baseline.json (module "design-rules").
"""

from __future__ import annotations

from typing import Annotated, Any, Dict, List, Literal, Optional, Union

from pydantic import BaseModel, Field

from kicad_mcp.toolsets._common import dispatch_command

class CheckClearanceItem1Position(BaseModel):
    """Position to check (if ID not provided)"""

    x: Optional[float] = None
    y: Optional[float] = None
    unit: Optional[Literal["mm", "mil", "inch"]] = None


class CheckClearanceItem1(BaseModel):
    """First item to check"""

    type: Annotated[Literal["track", "via", "pad", "zone", "component"], Field(description="Type of the first item")]
    id: Annotated[Optional[str], Field(description="ID of the first item (if applicable)")] = None
    reference: Annotated[Optional[str], Field(description="Reference designator (for component)")] = None
    position: Annotated[Optional[CheckClearanceItem1Position], Field(description="Position to check (if ID not provided)")] = None


class CheckClearanceItem2Position(BaseModel):
    """Position to check (if ID not provided)"""

    x: Optional[float] = None
    y: Optional[float] = None
    unit: Optional[Literal["mm", "mil", "inch"]] = None


class CheckClearanceItem2(BaseModel):
    """Second item to check"""

    type: Annotated[Literal["track", "via", "pad", "zone", "component"], Field(description="Type of the second item")]
    id: Annotated[Optional[str], Field(description="ID of the second item (if applicable)")] = None
    reference: Annotated[Optional[str], Field(description="Reference designator (for component)")] = None
    position: Annotated[Optional[CheckClearanceItem2Position], Field(description="Position to check (if ID not provided)")] = None

def add_net_class(
    name: Annotated[str, Field(description="Name of the net class")],
    clearance: Annotated[float, Field(description="Clearance for this net class (mm)")],
    trackWidth: Annotated[float, Field(description="Track width for this net class (mm)")],
    viaDiameter: Annotated[float, Field(description="Via diameter for this net class (mm)")],
    viaDrill: Annotated[float, Field(description="Via drill size for this net class (mm)")],
    description: Annotated[Optional[str], Field(description="Optional description of the net class")] = None,
    uvia_diameter: Annotated[Optional[float], Field(description="Micro via diameter for this net class (mm)")] = None,
    uvia_drill: Annotated[Optional[float], Field(description="Micro via drill size for this net class (mm)")] = None,
    diff_pair_width: Annotated[Optional[float], Field(description="Differential pair width for this net class (mm)")] = None,
    diff_pair_gap: Annotated[Optional[float], Field(description="Differential pair gap for this net class (mm)")] = None,
    nets: Annotated[Optional[List[str]], Field(description="Array of net names to assign to this class")] = None,
) -> dict[str, Any]:
    """Create a named net class with specific design rules (clearance, track width, via size) and assign nets to it."""
    return dispatch_command("add_net_class", {"name": name, "clearance": clearance, "trackWidth": trackWidth, "viaDiameter": viaDiameter, "viaDrill": viaDrill, "description": description, "uvia_diameter": uvia_diameter, "uvia_drill": uvia_drill, "diff_pair_width": diff_pair_width, "diff_pair_gap": diff_pair_gap, "nets": nets})


def assign_net_to_class(
    net: Annotated[str, Field(description="Name of the net")],
    netClass: Annotated[str, Field(description="Name of the net class")],
) -> dict[str, Any]:
    """Assign a net to an existing net class to apply its specific design rules."""
    return dispatch_command("assign_net_to_class", {"net": net, "netClass": netClass})


def check_clearance(
    item1: Annotated[CheckClearanceItem1, Field(description="First item to check")],
    item2: Annotated[CheckClearanceItem2, Field(description="Second item to check")],
) -> dict[str, Any]:
    """Check the actual clearance between two PCB items (track, via, pad, zone or component) and report whether it meets the design rules."""
    return dispatch_command("check_clearance", {"item1": item1, "item2": item2})


def get_design_rules() -> dict[str, Any]:
    """Return the current PCB design rules (clearance, track width, via sizes, courtyard settings)."""
    return dispatch_command("get_design_rules", {})


def get_drc_violations(
    severity: Annotated[Optional[Literal["error", "warning", "all"]], Field(description="Filter violations by severity")] = None,
) -> dict[str, Any]:
    """Return the list of current DRC violations on the PCB, optionally filtered by severity (error, warning)."""
    return dispatch_command("get_drc_violations", {"severity": severity})


def run_drc(
    reportPath: Annotated[Optional[str], Field(description="Optional path to save the DRC report")] = None,
) -> dict[str, Any]:
    """Run the KiCAD Design Rule Check (DRC) on the current PCB and return violations. Optionally save the report to a file."""
    return dispatch_command("run_drc", {"reportPath": reportPath})


def set_design_rules(
    clearance: Annotated[Optional[float], Field(description="Minimum clearance between copper items (mm)")] = None,
    trackWidth: Annotated[Optional[float], Field(description="Default track width (mm)")] = None,
    viaDiameter: Annotated[Optional[float], Field(description="Default via diameter (mm)")] = None,
    viaDrill: Annotated[Optional[float], Field(description="Default via drill size (mm)")] = None,
    microViaDiameter: Annotated[Optional[float], Field(description="Default micro via diameter (mm)")] = None,
    microViaDrill: Annotated[Optional[float], Field(description="Default micro via drill size (mm)")] = None,
    minTrackWidth: Annotated[Optional[float], Field(description="Minimum track width (mm)")] = None,
    minViaDiameter: Annotated[Optional[float], Field(description="Minimum via diameter (mm)")] = None,
    minViaDrill: Annotated[Optional[float], Field(description="Minimum via drill size (mm)")] = None,
    minMicroViaDiameter: Annotated[Optional[float], Field(description="Minimum micro via diameter (mm)")] = None,
    minMicroViaDrill: Annotated[Optional[float], Field(description="Minimum micro via drill size (mm)")] = None,
    minHoleDiameter: Annotated[Optional[float], Field(description="Minimum hole diameter (mm)")] = None,
    requireCourtyard: Annotated[Optional[bool], Field(description="Whether to require courtyards for all footprints")] = None,
    courtyardClearance: Annotated[Optional[float], Field(description="Minimum clearance between courtyards (mm)")] = None,
) -> dict[str, Any]:
    """Configure PCB design rules: clearance, track width, via dimensions and courtyard requirements."""
    return dispatch_command("set_design_rules", {"clearance": clearance, "trackWidth": trackWidth, "viaDiameter": viaDiameter, "viaDrill": viaDrill, "microViaDiameter": microViaDiameter, "microViaDrill": microViaDrill, "minTrackWidth": minTrackWidth, "minViaDiameter": minViaDiameter, "minViaDrill": minViaDrill, "minMicroViaDiameter": minMicroViaDiameter, "minMicroViaDrill": minMicroViaDrill, "minHoleDiameter": minHoleDiameter, "requireCourtyard": requireCourtyard, "courtyardClearance": courtyardClearance})


def set_layer_constraints(
    layer: Annotated[str, Field(description="Layer name (e.g., 'F.Cu')")],
    minTrackWidth: Annotated[Optional[float], Field(description="Minimum track width for this layer (mm)")] = None,
    minClearance: Annotated[Optional[float], Field(description="Minimum clearance for this layer (mm)")] = None,
    minViaDiameter: Annotated[Optional[float], Field(description="Minimum via diameter for this layer (mm)")] = None,
    minViaDrill: Annotated[Optional[float], Field(description="Minimum via drill size for this layer (mm)")] = None,
) -> dict[str, Any]:
    """Set per-layer design rule constraints (minimum track width, clearance and via dimensions)."""
    return dispatch_command("set_layer_constraints", {"layer": layer, "minTrackWidth": minTrackWidth, "minClearance": minClearance, "minViaDiameter": minViaDiameter, "minViaDrill": minViaDrill})


_TOOLS = [
    add_net_class,
    assign_net_to_class,
    check_clearance,
    get_design_rules,
    get_drc_violations,
    run_drc,
    set_design_rules,
    set_layer_constraints,
]


def register(mcp: Any) -> None:
    for fn in _TOOLS:
        mcp.tool()(fn)
