"""eagle toolset — GENERATED by scripts/gen_toolsets.py, do not hand-edit.

Source of truth: tests/fixtures/tools_baseline.json (module "eagle").
"""

from __future__ import annotations

from typing import Annotated, Any, Dict, List, Literal, Optional, Union

from pydantic import BaseModel, Field

from kicad_mcp.toolsets._common import dispatch_command

def import_eagle_project(
    board_file: Annotated[str, Field(description="Absolute path to the Eagle .brd board file")],
    schematic_file: Annotated[Optional[str], Field(description="Absolute path to the Eagle .sch schematic file (auto-detected from .brd path if omitted)")] = None,
    output_dir: Annotated[Optional[str], Field(description="Output directory for the KiCad project (defaults to a subdirectory next to the .brd file)")] = None,
    project_name: Annotated[Optional[str], Field(description="KiCad project name (defaults to the .brd filename without extension)")] = None,
) -> dict[str, Any]:
    """Import an Eagle project (.brd + .sch) and convert it to a KiCad project. Converts the PCB layout via kicad-cli and translates the schematic from Eagle XML to KiCad S-expression format."""
    return dispatch_command("import_eagle_project", {"board_file": board_file, "schematic_file": schematic_file, "output_dir": output_dir, "project_name": project_name})


_TOOLS = [
    import_eagle_project,
]


def register(mcp: Any) -> None:
    for fn in _TOOLS:
        mcp.tool()(fn)
