"""export toolset — GENERATED by scripts/gen_toolsets.py, do not hand-edit.

Source of truth: tests/fixtures/tools_baseline.json (module "export").
"""

from __future__ import annotations

from typing import Annotated, Any, Dict, List, Literal, Optional, Union

from pydantic import BaseModel, Field

from kicad_mcp.toolsets._common import dispatch_command

def export_3d(
    outputPath: Annotated[str, Field(description="Path to save the 3D model file")],
    format: Annotated[Literal["STEP", "STL", "VRML", "OBJ"], Field(description="3D model format")],
    includeComponents: Annotated[Optional[bool], Field(description="Whether to include 3D component models")] = None,
    includeCopper: Annotated[Optional[bool], Field(description="Whether to include copper layers")] = None,
    includeSolderMask: Annotated[Optional[bool], Field(description="Whether to include solder mask")] = None,
    includeSilkscreen: Annotated[Optional[bool], Field(description="Whether to include silkscreen")] = None,
) -> dict[str, Any]:
    """Export the PCB as a 3D model (STEP, STL, VRML or OBJ) including optional copper, solder mask, silkscreen and component 3D models."""
    return dispatch_command("export_3d", {"outputPath": outputPath, "format": format, "includeComponents": includeComponents, "includeCopper": includeCopper, "includeSolderMask": includeSolderMask, "includeSilkscreen": includeSilkscreen})


def export_3d_cli(
    outputPath: Annotated[str, Field(description="Output 3D model file path")],
    format: Annotated[Literal["step", "glb", "stl", "ply", "brep", "xao", "vrml"], Field(description="3D output format (selects the kicad-cli subcommand)")],
    boardPath: Annotated[Optional[str], Field(description="Path to the .kicad_pcb (default: current board)")] = None,
    defineVar: Annotated[Optional[List[str]], Field(description="Project variable overrides as 'KEY=VALUE' strings")] = None,
    force: Annotated[Optional[bool], Field(description="Overwrite output file")] = None,
    noUnspecified: Annotated[Optional[bool], Field(description="Exclude 3D models for components with 'Unspecified' footprint type")] = None,
    noDnp: Annotated[Optional[bool], Field(description="Exclude 3D models for components with 'Do not populate' attribute")] = None,
    userOrigin: Annotated[Optional[str], Field(description="User-specified output origin e.g. '1x1in', '25.4x25.4mm' (default unit mm)")] = None,
    gridOrigin: Annotated[Optional[bool], Field(description="Use Grid Origin for output origin")] = None,
    drillOrigin: Annotated[Optional[bool], Field(description="Use Drill Origin for output origin")] = None,
    substModels: Annotated[Optional[bool], Field(description="Substitute STEP/IGS models in place of VRML models")] = None,
    boardOnly: Annotated[Optional[bool], Field(description="Only generate a board with no components")] = None,
    cutViasInBody: Annotated[Optional[bool], Field(description="Cut via holes in board body even if conductor layers not exported")] = None,
    noBoardBody: Annotated[Optional[bool], Field(description="Exclude board body")] = None,
    noComponents: Annotated[Optional[bool], Field(description="Exclude 3D models for components")] = None,
    componentFilter: Annotated[Optional[str], Field(description="Only include component models matching this refdes list (comma, wildcards)")] = None,
    includeTracks: Annotated[Optional[bool], Field(description="Export tracks and vias")] = None,
    includePads: Annotated[Optional[bool], Field(description="Export pads")] = None,
    includeZones: Annotated[Optional[bool], Field(description="Export zones")] = None,
    includeInnerCopper: Annotated[Optional[bool], Field(description="Export elements on inner copper layers")] = None,
    includeSilkscreen: Annotated[Optional[bool], Field(description="Export silkscreen graphics as flat faces")] = None,
    includeSoldermask: Annotated[Optional[bool], Field(description="Export soldermask layers as flat faces")] = None,
    fuseShapes: Annotated[Optional[bool], Field(description="Fuse overlapping geometry together")] = None,
    fillAllVias: Annotated[Optional[bool], Field(description="Don't cut via holes in conductor layers")] = None,
    minDistance: Annotated[Optional[str], Field(description="Min distance between points to treat as separate (default '0.01mm')")] = None,
    netFilter: Annotated[Optional[str], Field(description="Only include copper items belonging to nets matching this wildcard")] = None,
    noOptimizeStep: Annotated[Optional[bool], Field(description="Do not optimize STEP file (enables writing parametric curves; STEP only)")] = None,
    units: Annotated[Optional[Literal["mm", "m", "in", "tenths"]], Field(description="Output units (VRML only; default in)")] = None,
    modelsDir: Annotated[Optional[str], Field(description="Folder to store 3D models in (VRML only; empty = embed in main file)")] = None,
    modelsRelative: Annotated[Optional[bool], Field(description="Use relative model paths with modelsDir (VRML only)")] = None,
) -> dict[str, Any]:
    """Export a 3D model of the PCB via kicad-cli. The `format` param selects the subcommand (step, glb, stl, ply, brep, xao, vrml); only flags valid for that subcommand are forwarded. STEP/glb/stl/ply/brep/xao share the geometry/include flag set (no-board-body, include-tracks/pads/zones/inner-copper/silkscreen/soldermask, fuse-shapes, fill-all-vias, component/net filters, min-distance, etc.; no-optimize-step is STEP-only); vrml uses units + models-dir/models-relative instead. Rich CLI sibling of export_3d and export_vrml. Reads the last SAVED state of the .kicad_pcb."""
    return dispatch_command("export_3d_cli", {"outputPath": outputPath, "format": format, "boardPath": boardPath, "defineVar": defineVar, "force": force, "noUnspecified": noUnspecified, "noDnp": noDnp, "userOrigin": userOrigin, "gridOrigin": gridOrigin, "drillOrigin": drillOrigin, "substModels": substModels, "boardOnly": boardOnly, "cutViasInBody": cutViasInBody, "noBoardBody": noBoardBody, "noComponents": noComponents, "componentFilter": componentFilter, "includeTracks": includeTracks, "includePads": includePads, "includeZones": includeZones, "includeInnerCopper": includeInnerCopper, "includeSilkscreen": includeSilkscreen, "includeSoldermask": includeSoldermask, "fuseShapes": fuseShapes, "fillAllVias": fillAllVias, "minDistance": minDistance, "netFilter": netFilter, "noOptimizeStep": noOptimizeStep, "units": units, "modelsDir": modelsDir, "modelsRelative": modelsRelative})


def export_bom(
    outputPath: Annotated[str, Field(description="Path to save the BOM file")],
    format: Annotated[Literal["CSV", "XML", "HTML", "JSON"], Field(description="BOM file format")],
    groupByValue: Annotated[Optional[bool], Field(description="Whether to group components by value")] = None,
    includeAttributes: Annotated[Optional[List[str]], Field(description="Optional array of additional attributes to include")] = None,
) -> dict[str, Any]:
    """Export a Bill of Materials (BOM) from the PCB in CSV, XML, HTML or JSON format."""
    return dispatch_command("export_bom", {"outputPath": outputPath, "format": format, "groupByValue": groupByValue, "includeAttributes": includeAttributes})


def export_drill(
    outputDir: Annotated[str, Field(description="Output directory for the drill files")],
    boardPath: Annotated[Optional[str], Field(description="Path to the .kicad_pcb (default: current board)")] = None,
    format: Annotated[Optional[Literal["excellon", "gerber"]], Field(description="Drill file format (default excellon)")] = None,
    drillOrigin: Annotated[Optional[Literal["absolute", "plot"]], Field(description="Drill coordinate origin (default absolute)")] = None,
    excellonZerosFormat: Annotated[Optional[Literal["decimal", "suppressleading", "suppresstrailing", "keep"]], Field(description="Excellon zero-suppression format (default decimal)")] = None,
    excellonOvalFormat: Annotated[Optional[Literal["route", "alternate"]], Field(description="Excellon oval hole format (default alternate)")] = None,
    excellonUnits: Annotated[Optional[Literal["in", "mm"]], Field(description="Excellon output units (default mm)")] = None,
    excellonMirrorY: Annotated[Optional[bool], Field(description="Mirror the Y axis (Excellon)")] = None,
    excellonMinHeader: Annotated[Optional[bool], Field(description="Use a minimal Excellon header")] = None,
    excellonSeparateTh: Annotated[Optional[bool], Field(description="Generate independent files for NPTH and PTH holes")] = None,
    generateMap: Annotated[Optional[bool], Field(description="Generate a drill map / summary file")] = None,
    mapFormat: Annotated[Optional[Literal["pdf", "gerberx2", "ps", "dxf", "svg"]], Field(description="Drill map format when generateMap is set (default pdf)")] = None,
    gerberPrecision: Annotated[Optional[float], Field(description="Gerber coordinate precision (5 or 6) when format=gerber")] = None,
) -> dict[str, Any]:
    """Generate drill files for a PCB via kicad-cli, exposing the full Excellon/Gerber drill option set (format, drill origin, zero suppression, oval format, units, mirror-Y, minimal header, separate PTH/NPTH files, drill map + map format). Reads the last SAVED state of the .kicad_pcb."""
    return dispatch_command("export_drill", {"outputDir": outputDir, "boardPath": boardPath, "format": format, "drillOrigin": drillOrigin, "excellonZerosFormat": excellonZerosFormat, "excellonOvalFormat": excellonOvalFormat, "excellonUnits": excellonUnits, "excellonMirrorY": excellonMirrorY, "excellonMinHeader": excellonMinHeader, "excellonSeparateTh": excellonSeparateTh, "generateMap": generateMap, "mapFormat": mapFormat, "gerberPrecision": gerberPrecision})


def export_gencad(
    outputPath: Annotated[str, Field(description="Output .cad file path")],
    boardPath: Annotated[Optional[str], Field(description="Path to the .kicad_pcb (default: current board)")] = None,
    defineVar: Annotated[Optional[List[str]], Field(description="Project variable overrides as 'KEY=VALUE' strings")] = None,
    flipBottomPads: Annotated[Optional[bool], Field(description="Flip bottom footprint padstacks")] = None,
    uniquePins: Annotated[Optional[bool], Field(description="Generate unique pin names")] = None,
    uniqueFootprints: Annotated[Optional[bool], Field(description="Generate a new shape for each footprint instance (do not reuse shapes)")] = None,
    useDrillOrigin: Annotated[Optional[bool], Field(description="Use drill/place file origin as origin")] = None,
    storeOriginCoord: Annotated[Optional[bool], Field(description="Save the origin coordinates in the file")] = None,
) -> dict[str, Any]:
    """Export the PCB in GenCAD format via kicad-cli. Assembly/test interchange format. Exposes padstack flip, unique pin/footprint shape generation, drill-file origin, and store-origin-coordinate options. Reads the last SAVED state of the .kicad_pcb."""
    return dispatch_command("export_gencad", {"outputPath": outputPath, "boardPath": boardPath, "defineVar": defineVar, "flipBottomPads": flipBottomPads, "uniquePins": uniquePins, "uniqueFootprints": uniqueFootprints, "useDrillOrigin": useDrillOrigin, "storeOriginCoord": storeOriginCoord})


def export_gerber(
    outputDir: Annotated[str, Field(description="Directory to save Gerber files")],
    layers: Annotated[Optional[List[str]], Field(description="Optional array of layer names to export (default: all)")] = None,
    useProtelExtensions: Annotated[Optional[bool], Field(description="Whether to use Protel filename extensions")] = None,
    generateDrillFiles: Annotated[Optional[bool], Field(description="Whether to generate drill files")] = None,
    generateMapFile: Annotated[Optional[bool], Field(description="Whether to generate a map file")] = None,
    useAuxOrigin: Annotated[Optional[bool], Field(description="Whether to use auxiliary axis as origin")] = None,
) -> dict[str, Any]:
    """Export PCB Gerber manufacturing files to a directory. Optionally include drill files, map files and choose layer subset."""
    return dispatch_command("export_gerber", {"outputDir": outputDir, "layers": layers, "useProtelExtensions": useProtelExtensions, "generateDrillFiles": generateDrillFiles, "generateMapFile": generateMapFile, "useAuxOrigin": useAuxOrigin})


def export_gerber_single(
    outputPath: Annotated[str, Field(description="Output Gerber file path")],
    boardPath: Annotated[Optional[str], Field(description="Path to the .kicad_pcb (default: current board)")] = None,
    layers: Annotated[Optional[List[str]], Field(description="Layers to plot, untranslated names e.g. ['F.Cu','B.Cu','Edge.Cuts']")] = None,
    commonLayers: Annotated[Optional[List[str]], Field(description="Layers to include on every plot (e.g. ['Edge.Cuts'])")] = None,
    drawingSheet: Annotated[Optional[str], Field(description="Path to a drawing sheet override")] = None,
    defineVar: Annotated[Optional[List[str]], Field(description="Project variable overrides as 'KEY=VALUE' strings")] = None,
    excludeRefdes: Annotated[Optional[bool], Field(description="Exclude reference designator text")] = None,
    excludeValue: Annotated[Optional[bool], Field(description="Exclude value text")] = None,
    includeBorderTitle: Annotated[Optional[bool], Field(description="Include the border and title block")] = None,
    sketchPadsOnFabLayers: Annotated[Optional[bool], Field(description="Draw pad outlines and numbers on fab layers")] = None,
    hideDnpFootprintsOnFabLayers: Annotated[Optional[bool], Field(description="Don't plot DNP footprint text/graphics on fab layers")] = None,
    sketchDnpFootprintsOnFabLayers: Annotated[Optional[bool], Field(description="Plot DNP footprints in sketch mode on fab layers")] = None,
    crossoutDnpFootprintsOnFabLayers: Annotated[Optional[bool], Field(description="Plot an 'X' over DNP footprint courtyards and strike out their refdes")] = None,
    noX2: Annotated[Optional[bool], Field(description="Do not use the extended X2 Gerber format")] = None,
    noNetlist: Annotated[Optional[bool], Field(description="Do not generate netlist attributes")] = None,
    subtractSoldermask: Annotated[Optional[bool], Field(description="Subtract soldermask from silkscreen")] = None,
    disableApertureMacros: Annotated[Optional[bool], Field(description="Disable aperture macros")] = None,
    useDrillFileOrigin: Annotated[Optional[bool], Field(description="Use the drill/place file origin")] = None,
    noProtelExt: Annotated[Optional[bool], Field(description="Use KiCad Gerber file extensions instead of Protel")] = None,
    precision: Annotated[Optional[float], Field(description="Gerber coordinate precision: 5 or 6 (default 6)")] = None,
) -> dict[str, Any]:
    """Plot the given layers to a SINGLE Gerber file via kicad-cli (`pcb export gerber`). Singular sibling of export_gerbers. Exposes the full single-file Plot option set (X2, netlist attributes, DNP fab-layer modes, soldermask subtraction, aperture macros, drill-file origin, precision, Protel extension). Reads the last SAVED state of the .kicad_pcb."""
    return dispatch_command("export_gerber_single", {"outputPath": outputPath, "boardPath": boardPath, "layers": layers, "commonLayers": commonLayers, "drawingSheet": drawingSheet, "defineVar": defineVar, "excludeRefdes": excludeRefdes, "excludeValue": excludeValue, "includeBorderTitle": includeBorderTitle, "sketchPadsOnFabLayers": sketchPadsOnFabLayers, "hideDnpFootprintsOnFabLayers": hideDnpFootprintsOnFabLayers, "sketchDnpFootprintsOnFabLayers": sketchDnpFootprintsOnFabLayers, "crossoutDnpFootprintsOnFabLayers": crossoutDnpFootprintsOnFabLayers, "noX2": noX2, "noNetlist": noNetlist, "subtractSoldermask": subtractSoldermask, "disableApertureMacros": disableApertureMacros, "useDrillFileOrigin": useDrillFileOrigin, "noProtelExt": noProtelExt, "precision": precision})


def export_gerbers(
    outputDir: Annotated[str, Field(description="Output directory for the Gerber files")],
    boardPath: Annotated[Optional[str], Field(description="Path to the .kicad_pcb (default: current board)")] = None,
    layers: Annotated[Optional[List[str]], Field(description="Layers to plot, untranslated names e.g. ['F.Cu','B.Cu','Edge.Cuts']")] = None,
    commonLayers: Annotated[Optional[List[str]], Field(description="Layers to include on every plot (e.g. ['Edge.Cuts'])")] = None,
    drawingSheet: Annotated[Optional[str], Field(description="Path to a drawing sheet override")] = None,
    defineVar: Annotated[Optional[List[str]], Field(description="Project variable overrides as 'KEY=VALUE' strings")] = None,
    excludeRefdes: Annotated[Optional[bool], Field(description="Exclude reference designator text")] = None,
    excludeValue: Annotated[Optional[bool], Field(description="Exclude value text")] = None,
    includeBorderTitle: Annotated[Optional[bool], Field(description="Include border and title block")] = None,
    sketchPadsOnFabLayers: Annotated[Optional[bool], Field(description="Draw pad outlines and numbers on fab layers")] = None,
    hideDnpFootprintsOnFabLayers: Annotated[Optional[bool], Field(description="Don't plot DNP footprint text/graphics on fab layers")] = None,
    sketchDnpFootprintsOnFabLayers: Annotated[Optional[bool], Field(description="Plot DNP footprints in sketch mode on fab layers")] = None,
    crossoutDnpFootprintsOnFabLayers: Annotated[Optional[bool], Field(description="Plot an 'X' over DNP footprint courtyards and strike out their refdes")] = None,
    noX2: Annotated[Optional[bool], Field(description="Do not use the extended X2 Gerber format")] = None,
    noNetlist: Annotated[Optional[bool], Field(description="Do not generate netlist attributes")] = None,
    subtractSoldermask: Annotated[Optional[bool], Field(description="Subtract soldermask from silkscreen")] = None,
    disableApertureMacros: Annotated[Optional[bool], Field(description="Disable aperture macros")] = None,
    useDrillFileOrigin: Annotated[Optional[bool], Field(description="Use the drill/place file origin")] = None,
    noProtelExt: Annotated[Optional[bool], Field(description="Use KiCad Gerber file extensions instead of Protel")] = None,
    boardPlotParams: Annotated[Optional[bool], Field(description="Use the Gerber plot settings already stored in the board file")] = None,
    precision: Annotated[Optional[float], Field(description="Gerber coordinate precision: 5 or 6 (default 6)")] = None,
) -> dict[str, Any]:
    """Plot Gerber files for a PCB via kicad-cli, exposing the full Plot-dialog option set (X2, netlist attributes, DNP handling, soldermask subtraction, precision, drill-file origin, stored board plot settings, etc). Reads the board from disk, so it reflects the last SAVED state of the .kicad_pcb."""
    return dispatch_command("export_gerbers", {"outputDir": outputDir, "boardPath": boardPath, "layers": layers, "commonLayers": commonLayers, "drawingSheet": drawingSheet, "defineVar": defineVar, "excludeRefdes": excludeRefdes, "excludeValue": excludeValue, "includeBorderTitle": includeBorderTitle, "sketchPadsOnFabLayers": sketchPadsOnFabLayers, "hideDnpFootprintsOnFabLayers": hideDnpFootprintsOnFabLayers, "sketchDnpFootprintsOnFabLayers": sketchDnpFootprintsOnFabLayers, "crossoutDnpFootprintsOnFabLayers": crossoutDnpFootprintsOnFabLayers, "noX2": noX2, "noNetlist": noNetlist, "subtractSoldermask": subtractSoldermask, "disableApertureMacros": disableApertureMacros, "useDrillFileOrigin": useDrillFileOrigin, "noProtelExt": noProtelExt, "boardPlotParams": boardPlotParams, "precision": precision})


def export_ipc2581(
    outputPath: Annotated[str, Field(description="Output .xml file path")],
    boardPath: Annotated[Optional[str], Field(description="Path to the .kicad_pcb (default: current board)")] = None,
    drawingSheet: Annotated[Optional[str], Field(description="Path to a drawing sheet override")] = None,
    defineVar: Annotated[Optional[List[str]], Field(description="Project variable overrides as 'KEY=VALUE' strings")] = None,
    precision: Annotated[Optional[float], Field(description="Coordinate precision (default 6)")] = None,
    compress: Annotated[Optional[bool], Field(description="Compress the output")] = None,
    version: Annotated[Optional[str], Field(description="IPC-2581 standard version (default 'C')")] = None,
    units: Annotated[Optional[Literal["mm", "in"]], Field(description="Units (default mm)")] = None,
    bomColIntId: Annotated[Optional[str], Field(description="Schematic field to use for the BOM Internal Id column")] = None,
    bomColMfgPn: Annotated[Optional[str], Field(description="Schematic field to use for the BOM Manufacturer Part Number column")] = None,
    bomColMfg: Annotated[Optional[str], Field(description="Schematic field to use for the BOM Manufacturer column")] = None,
    bomColDistPn: Annotated[Optional[str], Field(description="Schematic field to use for the BOM Distributor Part Number column")] = None,
    bomColDist: Annotated[Optional[str], Field(description="Value to insert into the BOM Distributor column")] = None,
) -> dict[str, Any]:
    """Export the PCB in IPC-2581 format via kicad-cli. Single-file MES/CAD interchange carrying placement, nets and BOM part data inline. The bomCol* params map schematic fields to the embedded BOM columns (e.g. internal P/N, manufacturer P/N) — useful for assembly/MES imports. Reads the last SAVED state of the .kicad_pcb."""
    return dispatch_command("export_ipc2581", {"outputPath": outputPath, "boardPath": boardPath, "drawingSheet": drawingSheet, "defineVar": defineVar, "precision": precision, "compress": compress, "version": version, "units": units, "bomColIntId": bomColIntId, "bomColMfgPn": bomColMfgPn, "bomColMfg": bomColMfg, "bomColDistPn": bomColDistPn, "bomColDist": bomColDist})


def export_ipcd356(
    outputPath: Annotated[str, Field(description="Output .ipc / netlist file path")],
    boardPath: Annotated[Optional[str], Field(description="Path to the .kicad_pcb (default: current board)")] = None,
) -> dict[str, Any]:
    """Generate an IPC-D-356 bare-board electrical-test netlist via kicad-cli. Consumed by flying-probe and bed-of-nails testers. Reads the last SAVED state of the .kicad_pcb."""
    return dispatch_command("export_ipcd356", {"outputPath": outputPath, "boardPath": boardPath})


def export_netlist(
    schematicPath: Annotated[str, Field(description="Absolute path to the .kicad_sch schematic file")],
    outputPath: Annotated[str, Field(description="Absolute path for the output file (e.g. /tmp/design.spice)")],
    format: Annotated[Optional[Literal["KiCad", "Spice", "Cadstar", "OrcadPCB2"]], Field(description="Netlist format (default: KiCad)")] = None,
) -> dict[str, Any]:
    """Export the schematic netlist to a file using kicad-cli. Supports KiCad XML (default), Spice (for simulation), Cadstar, and OrcadPCB2 formats. Use this when you need to write a netlist file to disk — for example to produce a SPICE file for simulation or to diff against a reference. To get net/component data inline without writing a file, use generate_netlist instead."""
    return dispatch_command("export_netlist", {"schematicPath": schematicPath, "outputPath": outputPath, "format": format})


def export_odb(
    outputPath: Annotated[str, Field(description="Output file path (archive or directory per compression)")],
    boardPath: Annotated[Optional[str], Field(description="Path to the .kicad_pcb (default: current board)")] = None,
    drawingSheet: Annotated[Optional[str], Field(description="Path to a drawing sheet override")] = None,
    defineVar: Annotated[Optional[List[str]], Field(description="Project variable overrides as 'KEY=VALUE' strings")] = None,
    precision: Annotated[Optional[float], Field(description="Coordinate precision (default 2)")] = None,
    compression: Annotated[Optional[Literal["zip", "tgz", "none"]], Field(description="Output container/compression mode (default zip)")] = None,
    units: Annotated[Optional[Literal["mm", "in"]], Field(description="Units (default mm)")] = None,
) -> dict[str, Any]:
    """Export the PCB in ODB++ format via kicad-cli. Single job archive (copper, drill, placement, components, nets, outline) widely used by CAM/MES/assembly. Reads the last SAVED state of the .kicad_pcb."""
    return dispatch_command("export_odb", {"outputPath": outputPath, "boardPath": boardPath, "drawingSheet": drawingSheet, "defineVar": defineVar, "precision": precision, "compression": compression, "units": units})


def export_pcb_dxf(
    outputPath: Annotated[str, Field(description="Output DXF file path (or directory in multi mode)")],
    boardPath: Annotated[Optional[str], Field(description="Path to the .kicad_pcb (default: current board)")] = None,
    layers: Annotated[Optional[List[str]], Field(description="Layers to plot, untranslated names e.g. ['F.Cu','B.Cu','Edge.Cuts']")] = None,
    commonLayers: Annotated[Optional[List[str]], Field(description="Layers to include on every plot (e.g. ['Edge.Cuts'])")] = None,
    drawingSheet: Annotated[Optional[str], Field(description="Path to a drawing sheet override")] = None,
    defineVar: Annotated[Optional[List[str]], Field(description="Project variable overrides as 'KEY=VALUE' strings")] = None,
    excludeRefdes: Annotated[Optional[bool], Field(description="Exclude reference designator text")] = None,
    excludeValue: Annotated[Optional[bool], Field(description="Exclude value text")] = None,
    sketchPadsOnFabLayers: Annotated[Optional[bool], Field(description="Draw pad outlines and numbers on fab layers")] = None,
    hideDnpFootprintsOnFabLayers: Annotated[Optional[bool], Field(description="Don't plot DNP footprint text/graphics on fab layers")] = None,
    sketchDnpFootprintsOnFabLayers: Annotated[Optional[bool], Field(description="Plot DNP footprints in sketch mode on fab layers")] = None,
    crossoutDnpFootprintsOnFabLayers: Annotated[Optional[bool], Field(description="Plot an 'X' over DNP footprint courtyards and strike out their refdes")] = None,
    subtractSoldermask: Annotated[Optional[bool], Field(description="Subtract soldermask from silkscreen")] = None,
    useContours: Annotated[Optional[bool], Field(description="Plot graphic items using their contours")] = None,
    useDrillOrigin: Annotated[Optional[bool], Field(description="Plot using the drill/place file origin")] = None,
    includeBorderTitle: Annotated[Optional[bool], Field(description="Include the border and title block")] = None,
    outputUnits: Annotated[Optional[Literal["mm", "in"]], Field(description="Output units (default in)")] = None,
    drillShapeOpt: Annotated[Optional[float], Field(description="Pad/via drill shape option (0 none, 1 small, 2 actual; default 2)")] = None,
    modeSingle: Annotated[Optional[bool], Field(description="Single file; output path is full path; LAYER_LIST controls all layers")] = None,
    modeMulti: Annotated[Optional[bool], Field(description="Multi output; output path is a directory (GUI-like plotting)")] = None,
) -> dict[str, Any]:
    """Plot the PCB layout to DXF via kicad-cli, exposing the full layer-plot option set (layer + common-layer lists, refdes/value exclusion, soldermask subtraction, use-contours, use-drill-origin, border+title, output units, DNP fab-layer modes, drill shape, single/multi output modes). Reads the last SAVED state of the .kicad_pcb."""
    return dispatch_command("export_pcb_dxf", {"outputPath": outputPath, "boardPath": boardPath, "layers": layers, "commonLayers": commonLayers, "drawingSheet": drawingSheet, "defineVar": defineVar, "excludeRefdes": excludeRefdes, "excludeValue": excludeValue, "sketchPadsOnFabLayers": sketchPadsOnFabLayers, "hideDnpFootprintsOnFabLayers": hideDnpFootprintsOnFabLayers, "sketchDnpFootprintsOnFabLayers": sketchDnpFootprintsOnFabLayers, "crossoutDnpFootprintsOnFabLayers": crossoutDnpFootprintsOnFabLayers, "subtractSoldermask": subtractSoldermask, "useContours": useContours, "useDrillOrigin": useDrillOrigin, "includeBorderTitle": includeBorderTitle, "outputUnits": outputUnits, "drillShapeOpt": drillShapeOpt, "modeSingle": modeSingle, "modeMulti": modeMulti})


def export_pcb_pdf(
    outputPath: Annotated[str, Field(description="Output PDF file path (or directory in separate mode)")],
    boardPath: Annotated[Optional[str], Field(description="Path to the .kicad_pcb (default: current board)")] = None,
    layers: Annotated[Optional[List[str]], Field(description="Layers to plot, untranslated names e.g. ['F.Cu','B.Cu','Edge.Cuts']")] = None,
    commonLayers: Annotated[Optional[List[str]], Field(description="Layers to include on every plot (e.g. ['Edge.Cuts'])")] = None,
    drawingSheet: Annotated[Optional[str], Field(description="Path to a drawing sheet override")] = None,
    defineVar: Annotated[Optional[List[str]], Field(description="Project variable overrides as 'KEY=VALUE' strings")] = None,
    mirror: Annotated[Optional[bool], Field(description="Mirror the board (to show bottom layers)")] = None,
    excludeRefdes: Annotated[Optional[bool], Field(description="Exclude reference designator text")] = None,
    excludeValue: Annotated[Optional[bool], Field(description="Exclude value text")] = None,
    includeBorderTitle: Annotated[Optional[bool], Field(description="Include the border and title block")] = None,
    subtractSoldermask: Annotated[Optional[bool], Field(description="Subtract soldermask from silkscreen")] = None,
    sketchPadsOnFabLayers: Annotated[Optional[bool], Field(description="Draw pad outlines and numbers on fab layers")] = None,
    hideDnpFootprintsOnFabLayers: Annotated[Optional[bool], Field(description="Don't plot DNP footprint text/graphics on fab layers")] = None,
    sketchDnpFootprintsOnFabLayers: Annotated[Optional[bool], Field(description="Plot DNP footprints in sketch mode on fab layers")] = None,
    crossoutDnpFootprintsOnFabLayers: Annotated[Optional[bool], Field(description="Plot an 'X' over DNP footprint courtyards and strike out their refdes")] = None,
    negative: Annotated[Optional[bool], Field(description="Plot as negative")] = None,
    blackAndWhite: Annotated[Optional[bool], Field(description="Black and white only")] = None,
    theme: Annotated[Optional[str], Field(description="Color theme to use (default: PCB editor settings)")] = None,
    drillShapeOpt: Annotated[Optional[float], Field(description="Pad/via drill shape option (0 none, 1 small, 2 actual; default 2)")] = None,
    modeSingle: Annotated[Optional[bool], Field(description="Single file; output path is full path; LAYER_LIST controls all layers")] = None,
    modeSeparate: Annotated[Optional[bool], Field(description="Plot the layers to individual PDF files")] = None,
    modeMultipage: Annotated[Optional[bool], Field(description="Plot the layers to a single multi-page PDF")] = None,
) -> dict[str, Any]:
    """Plot the PCB layout to PDF via kicad-cli, exposing the full layer-plot option set (layer + common-layer lists, mirror, refdes/value exclusion, border+title, soldermask subtraction, DNP fab-layer modes, negative, black-and-white, theme, drill shape, and single/separate/multipage output modes). Rich CLI sibling of export_pdf. Reads the last SAVED state of the .kicad_pcb."""
    return dispatch_command("export_pcb_pdf", {"outputPath": outputPath, "boardPath": boardPath, "layers": layers, "commonLayers": commonLayers, "drawingSheet": drawingSheet, "defineVar": defineVar, "mirror": mirror, "excludeRefdes": excludeRefdes, "excludeValue": excludeValue, "includeBorderTitle": includeBorderTitle, "subtractSoldermask": subtractSoldermask, "sketchPadsOnFabLayers": sketchPadsOnFabLayers, "hideDnpFootprintsOnFabLayers": hideDnpFootprintsOnFabLayers, "sketchDnpFootprintsOnFabLayers": sketchDnpFootprintsOnFabLayers, "crossoutDnpFootprintsOnFabLayers": crossoutDnpFootprintsOnFabLayers, "negative": negative, "blackAndWhite": blackAndWhite, "theme": theme, "drillShapeOpt": drillShapeOpt, "modeSingle": modeSingle, "modeSeparate": modeSeparate, "modeMultipage": modeMultipage})


def export_pcb_svg(
    outputPath: Annotated[str, Field(description="Output SVG file path (or directory in multi mode)")],
    boardPath: Annotated[Optional[str], Field(description="Path to the .kicad_pcb (default: current board)")] = None,
    layers: Annotated[Optional[List[str]], Field(description="Layers to plot, untranslated names e.g. ['F.Cu','B.Cu','Edge.Cuts']")] = None,
    commonLayers: Annotated[Optional[List[str]], Field(description="Layers to include on every plot (e.g. ['Edge.Cuts'])")] = None,
    drawingSheet: Annotated[Optional[str], Field(description="Path to a drawing sheet override")] = None,
    defineVar: Annotated[Optional[List[str]], Field(description="Project variable overrides as 'KEY=VALUE' strings")] = None,
    subtractSoldermask: Annotated[Optional[bool], Field(description="Subtract soldermask from silkscreen")] = None,
    mirror: Annotated[Optional[bool], Field(description="Mirror the board (to show bottom layers)")] = None,
    negative: Annotated[Optional[bool], Field(description="Plot as negative")] = None,
    blackAndWhite: Annotated[Optional[bool], Field(description="Black and white only")] = None,
    theme: Annotated[Optional[str], Field(description="Color theme to use (default: PCB editor settings)")] = None,
    sketchPadsOnFabLayers: Annotated[Optional[bool], Field(description="Draw pad outlines and numbers on fab layers")] = None,
    hideDnpFootprintsOnFabLayers: Annotated[Optional[bool], Field(description="Don't plot DNP footprint text/graphics on fab layers")] = None,
    sketchDnpFootprintsOnFabLayers: Annotated[Optional[bool], Field(description="Plot DNP footprints in sketch mode on fab layers")] = None,
    crossoutDnpFootprintsOnFabLayers: Annotated[Optional[bool], Field(description="Plot an 'X' over DNP footprint courtyards and strike out their refdes")] = None,
    pageSizeMode: Annotated[Optional[float], Field(description="Page sizing mode (0 frame+title block, 1 current page size, 2 board area only)")] = None,
    fitPageToBoard: Annotated[Optional[bool], Field(description="Fit the page to the board")] = None,
    excludeDrawingSheet: Annotated[Optional[bool], Field(description="No drawing sheet")] = None,
    drillShapeOpt: Annotated[Optional[float], Field(description="Pad/via drill shape option (0 none, 1 small, 2 actual; default 2)")] = None,
    modeSingle: Annotated[Optional[bool], Field(description="Single file; output path is full path; LAYER_LIST controls all layers")] = None,
    modeMulti: Annotated[Optional[bool], Field(description="Multi output; output path is a directory (GUI-like plotting)")] = None,
) -> dict[str, Any]:
    """Plot the PCB layout to SVG via kicad-cli, exposing the full layer-plot option set (layer + common-layer lists, mirror, soldermask subtraction, negative, black-and-white, theme, DNP fab-layer modes, page-size mode, fit-page-to-board, exclude-drawing-sheet, drill shape, single/multi output modes). Rich CLI sibling of export_svg. Reads the last SAVED state of the .kicad_pcb."""
    return dispatch_command("export_pcb_svg", {"outputPath": outputPath, "boardPath": boardPath, "layers": layers, "commonLayers": commonLayers, "drawingSheet": drawingSheet, "defineVar": defineVar, "subtractSoldermask": subtractSoldermask, "mirror": mirror, "negative": negative, "blackAndWhite": blackAndWhite, "theme": theme, "sketchPadsOnFabLayers": sketchPadsOnFabLayers, "hideDnpFootprintsOnFabLayers": hideDnpFootprintsOnFabLayers, "sketchDnpFootprintsOnFabLayers": sketchDnpFootprintsOnFabLayers, "crossoutDnpFootprintsOnFabLayers": crossoutDnpFootprintsOnFabLayers, "pageSizeMode": pageSizeMode, "fitPageToBoard": fitPageToBoard, "excludeDrawingSheet": excludeDrawingSheet, "drillShapeOpt": drillShapeOpt, "modeSingle": modeSingle, "modeMulti": modeMulti})


def export_pdf(
    outputPath: Annotated[str, Field(description="Path to save the PDF file")],
    layers: Annotated[Optional[List[str]], Field(description="Optional array of layer names to include (default: all)")] = None,
    blackAndWhite: Annotated[Optional[bool], Field(description="Whether to export in black and white")] = None,
    frameReference: Annotated[Optional[bool], Field(description="Whether to include frame reference")] = None,
    pageSize: Annotated[Optional[Literal["A4", "A3", "A2", "A1", "A0", "Letter", "Legal", "Tabloid"]], Field(description="Page size")] = None,
) -> dict[str, Any]:
    """Export the PCB layout as a PDF document, optionally selecting layers, page size and colour mode."""
    return dispatch_command("export_pdf", {"outputPath": outputPath, "layers": layers, "blackAndWhite": blackAndWhite, "frameReference": frameReference, "pageSize": pageSize})


def export_pos(
    outputPath: Annotated[str, Field(description="Output position file path")],
    boardPath: Annotated[Optional[str], Field(description="Path to the .kicad_pcb (default: current board)")] = None,
    side: Annotated[Optional[Literal["front", "back", "both"]], Field(description="Board side (gerber format only supports front or back; default both)")] = None,
    format: Annotated[Optional[Literal["ascii", "csv", "gerber"]], Field(description="Output format (default ascii)")] = None,
    units: Annotated[Optional[Literal["in", "mm"]], Field(description="Output units; ascii or csv format only (default in)")] = None,
    bottomNegateX: Annotated[Optional[bool], Field(description="Use negative X coordinates for bottom-layer footprints (ascii/csv only)")] = None,
    useDrillFileOrigin: Annotated[Optional[bool], Field(description="Use drill/place file origin (ascii/csv only)")] = None,
    smdOnly: Annotated[Optional[bool], Field(description="Include only SMD footprints (ascii/csv only)")] = None,
    excludeFpTh: Annotated[Optional[bool], Field(description="Exclude all footprints with through-hole pads (ascii/csv only)")] = None,
    excludeDnp: Annotated[Optional[bool], Field(description="Exclude all footprints with the Do Not Populate flag set")] = None,
    gerberBoardEdge: Annotated[Optional[bool], Field(description="Include board edge layer (Gerber only)")] = None,
) -> dict[str, Any]:
    """Generate a component placement (position / pick-and-place) file via kicad-cli, exposing the full CLI option set (side, format, units, bottom-negate-X, drill-file origin, SMD-only, exclude through-hole / DNP, gerber board edge). Rich CLI sibling of export_position_file. Reads the last SAVED state of the .kicad_pcb."""
    return dispatch_command("export_pos", {"outputPath": outputPath, "boardPath": boardPath, "side": side, "format": format, "units": units, "bottomNegateX": bottomNegateX, "useDrillFileOrigin": useDrillFileOrigin, "smdOnly": smdOnly, "excludeFpTh": excludeFpTh, "excludeDnp": excludeDnp, "gerberBoardEdge": gerberBoardEdge})


def export_position_file(
    outputPath: Annotated[str, Field(description="Path to save the position file")],
    format: Annotated[Optional[Literal["CSV", "ASCII"]], Field(description="File format (default: CSV)")] = None,
    units: Annotated[Optional[Literal["mm", "mil", "inch"]], Field(description="Units to use (default: mm)")] = None,
    side: Annotated[Optional[Literal["top", "bottom", "both"]], Field(description="Which board side to include (default: both)")] = None,
) -> dict[str, Any]:
    """Export a component placement/position file (pick-and-place) for PCB assembly in CSV or ASCII format."""
    return dispatch_command("export_position_file", {"outputPath": outputPath, "format": format, "units": units, "side": side})


def export_sch_bom(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch (required)")],
    outputPath: Annotated[str, Field(description="Output BOM file path")],
    preset: Annotated[Optional[str], Field(description="Named BOM preset from the schematic, e.g. 'Grouped By Value'")] = None,
    formatPreset: Annotated[Optional[str], Field(description="Named BOM format preset from the schematic, e.g. 'CSV'")] = None,
    fields: Annotated[Optional[str], Field(description="Ordered comma list of fields to export (supports special substitutions)")] = None,
    labels: Annotated[Optional[str], Field(description="Ordered comma list of labels to apply to the exported fields")] = None,
    groupBy: Annotated[Optional[str], Field(description="Fields to group references by when field values match")] = None,
    sortField: Annotated[Optional[str], Field(description="Field name to sort by (default Reference)")] = None,
    sortAsc: Annotated[Optional[str], Field(description="Sort ascending ('true') or descending ('false')")] = None,
    filter: Annotated[Optional[str], Field(description="Filter string to remove output lines")] = None,
    excludeDnp: Annotated[Optional[bool], Field(description="Exclude symbols marked Do-Not-Populate")] = None,
    includeExcludedFromBom: Annotated[Optional[bool], Field(description="Include symbols marked 'Exclude from BOM'")] = None,
    fieldDelimiter: Annotated[Optional[str], Field(description="Separator between output fields/columns (default ',')")] = None,
    stringDelimiter: Annotated[Optional[str], Field(description="Character to surround fields with (default '\"')")] = None,
    refDelimiter: Annotated[Optional[str], Field(description="Character between individual references (default ',')")] = None,
    refRangeDelimiter: Annotated[Optional[str], Field(description="Character for reference ranges; blank disables ranges (default '-')")] = None,
    keepTabs: Annotated[Optional[bool], Field(description="Keep tab characters from input fields")] = None,
    keepLineBreaks: Annotated[Optional[bool], Field(description="Keep line break characters from input fields")] = None,
) -> dict[str, Any]:
    """Generate a Bill of Materials from a schematic via kicad-cli (`sch export bom`), exposing the full option set (presets, field/label lists, grouping, sorting, filtering, DNP/excluded-from-BOM handling, and field/string/ref delimiters). schematicPath is REQUIRED."""
    return dispatch_command("export_sch_bom", {"schematicPath": schematicPath, "outputPath": outputPath, "preset": preset, "formatPreset": formatPreset, "fields": fields, "labels": labels, "groupBy": groupBy, "sortField": sortField, "sortAsc": sortAsc, "filter": filter, "excludeDnp": excludeDnp, "includeExcludedFromBom": includeExcludedFromBom, "fieldDelimiter": fieldDelimiter, "stringDelimiter": stringDelimiter, "refDelimiter": refDelimiter, "refRangeDelimiter": refRangeDelimiter, "keepTabs": keepTabs, "keepLineBreaks": keepLineBreaks})


def export_sch_dxf(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch (required)")],
    outputDir: Annotated[str, Field(description="Output directory for the DXF files")],
    drawingSheet: Annotated[Optional[str], Field(description="Path to a drawing sheet override")] = None,
    defineVar: Annotated[Optional[List[str]], Field(description="Project variable overrides as 'KEY=VALUE' strings")] = None,
    theme: Annotated[Optional[str], Field(description="Color theme to use (default: schematic settings)")] = None,
    blackAndWhite: Annotated[Optional[bool], Field(description="Black and white only")] = None,
    excludeDrawingSheet: Annotated[Optional[bool], Field(description="No drawing sheet")] = None,
    defaultFont: Annotated[Optional[str], Field(description="Default font name")] = None,
    pages: Annotated[Optional[str], Field(description="Comma list of page numbers to print (blank = all pages)")] = None,
) -> dict[str, Any]:
    """Export a schematic to DXF via kicad-cli (`sch export dxf`), one DXF per page into a directory. Exposes drawing-sheet override, theme, black-and-white, exclude-drawing-sheet, default-font, and page selection. schematicPath is REQUIRED."""
    return dispatch_command("export_sch_dxf", {"schematicPath": schematicPath, "outputDir": outputDir, "drawingSheet": drawingSheet, "defineVar": defineVar, "theme": theme, "blackAndWhite": blackAndWhite, "excludeDrawingSheet": excludeDrawingSheet, "defaultFont": defaultFont, "pages": pages})


def export_sch_hpgl(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch (required)")],
    outputDir: Annotated[str, Field(description="Output directory for the HPGL files")],
    drawingSheet: Annotated[Optional[str], Field(description="Path to a drawing sheet override")] = None,
    defineVar: Annotated[Optional[List[str]], Field(description="Project variable overrides as 'KEY=VALUE' strings")] = None,
    excludeDrawingSheet: Annotated[Optional[bool], Field(description="No drawing sheet")] = None,
    defaultFont: Annotated[Optional[str], Field(description="Default font name")] = None,
    pages: Annotated[Optional[str], Field(description="Comma list of page numbers to print (blank = all pages)")] = None,
    penSize: Annotated[Optional[float], Field(description="Pen size in mm (default 0.5)")] = None,
    origin: Annotated[Optional[float], Field(description="Origin and scale: 0 bottom left, 1 centered, 2 page fit, 3 content fit")] = None,
) -> dict[str, Any]:
    """Export a schematic to HPGL via kicad-cli (`sch export hpgl`), one plot per page into a directory. Exposes drawing-sheet override, exclude-drawing-sheet, default-font, page selection, pen size, and the origin/scale mode. schematicPath is REQUIRED."""
    return dispatch_command("export_sch_hpgl", {"schematicPath": schematicPath, "outputDir": outputDir, "drawingSheet": drawingSheet, "defineVar": defineVar, "excludeDrawingSheet": excludeDrawingSheet, "defaultFont": defaultFont, "pages": pages, "penSize": penSize, "origin": origin})


def export_sch_pdf(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch (required)")],
    outputPath: Annotated[str, Field(description="Output PDF file path")],
    drawingSheet: Annotated[Optional[str], Field(description="Path to a drawing sheet override")] = None,
    defineVar: Annotated[Optional[List[str]], Field(description="Project variable overrides as 'KEY=VALUE' strings")] = None,
    theme: Annotated[Optional[str], Field(description="Color theme to use (default: schematic settings)")] = None,
    blackAndWhite: Annotated[Optional[bool], Field(description="Black and white only")] = None,
    excludeDrawingSheet: Annotated[Optional[bool], Field(description="No drawing sheet")] = None,
    defaultFont: Annotated[Optional[str], Field(description="Default font name")] = None,
    excludePdfPropertyPopups: Annotated[Optional[bool], Field(description="Do not generate property popups in PDF")] = None,
    excludePdfHierarchicalLinks: Annotated[Optional[bool], Field(description="Do not generate clickable links for hierarchical elements in PDF")] = None,
    excludePdfMetadata: Annotated[Optional[bool], Field(description="Do not generate PDF metadata from AUTHOR and SUBJECT variables")] = None,
    noBackgroundColor: Annotated[Optional[bool], Field(description="Avoid setting a background color (regardless of theme)")] = None,
    pages: Annotated[Optional[str], Field(description="Comma list of page numbers to print (blank = all pages)")] = None,
) -> dict[str, Any]:
    """Export a schematic to PDF via kicad-cli (`sch export pdf`), exposing the full option set (drawing-sheet override, theme, black-and-white, exclude-drawing-sheet, default-font, the PDF property-popup / hierarchical-link / metadata excludes, no-background-color, and page selection). schematicPath is REQUIRED."""
    return dispatch_command("export_sch_pdf", {"schematicPath": schematicPath, "outputPath": outputPath, "drawingSheet": drawingSheet, "defineVar": defineVar, "theme": theme, "blackAndWhite": blackAndWhite, "excludeDrawingSheet": excludeDrawingSheet, "defaultFont": defaultFont, "excludePdfPropertyPopups": excludePdfPropertyPopups, "excludePdfHierarchicalLinks": excludePdfHierarchicalLinks, "excludePdfMetadata": excludePdfMetadata, "noBackgroundColor": noBackgroundColor, "pages": pages})


def export_sch_ps(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch (required)")],
    outputDir: Annotated[str, Field(description="Output directory for the PostScript files")],
    drawingSheet: Annotated[Optional[str], Field(description="Path to a drawing sheet override")] = None,
    defineVar: Annotated[Optional[List[str]], Field(description="Project variable overrides as 'KEY=VALUE' strings")] = None,
    theme: Annotated[Optional[str], Field(description="Color theme to use (default: schematic settings)")] = None,
    blackAndWhite: Annotated[Optional[bool], Field(description="Black and white only")] = None,
    excludeDrawingSheet: Annotated[Optional[bool], Field(description="No drawing sheet")] = None,
    defaultFont: Annotated[Optional[str], Field(description="Default font name")] = None,
    noBackgroundColor: Annotated[Optional[bool], Field(description="Avoid setting a background color (regardless of theme)")] = None,
    pages: Annotated[Optional[str], Field(description="Comma list of page numbers to print (blank = all pages)")] = None,
) -> dict[str, Any]:
    """Export a schematic to PostScript via kicad-cli (`sch export ps`), one PS per page into a directory. Exposes drawing-sheet override, theme, black-and-white, exclude-drawing-sheet, default-font, no-background-color, and page selection. schematicPath is REQUIRED."""
    return dispatch_command("export_sch_ps", {"schematicPath": schematicPath, "outputDir": outputDir, "drawingSheet": drawingSheet, "defineVar": defineVar, "theme": theme, "blackAndWhite": blackAndWhite, "excludeDrawingSheet": excludeDrawingSheet, "defaultFont": defaultFont, "noBackgroundColor": noBackgroundColor, "pages": pages})


def export_sch_python_bom(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch (required)")],
    outputPath: Annotated[str, Field(description="Output XML file path")],
) -> dict[str, Any]:
    """Export the legacy Python-BOM intermediate XML from a schematic via kicad-cli (`sch export python-bom`). This is the XML netlist consumed by the schematic editor's Python BOM scripts. Minimal option set (output + input only). schematicPath is REQUIRED."""
    return dispatch_command("export_sch_python_bom", {"schematicPath": schematicPath, "outputPath": outputPath})


def export_sch_svg(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch (required)")],
    outputDir: Annotated[str, Field(description="Output directory for the SVG files")],
    drawingSheet: Annotated[Optional[str], Field(description="Path to a drawing sheet override")] = None,
    defineVar: Annotated[Optional[List[str]], Field(description="Project variable overrides as 'KEY=VALUE' strings")] = None,
    theme: Annotated[Optional[str], Field(description="Color theme to use (default: schematic settings)")] = None,
    blackAndWhite: Annotated[Optional[bool], Field(description="Black and white only")] = None,
    excludeDrawingSheet: Annotated[Optional[bool], Field(description="No drawing sheet")] = None,
    defaultFont: Annotated[Optional[str], Field(description="Default font name")] = None,
    noBackgroundColor: Annotated[Optional[bool], Field(description="Avoid setting a background color (regardless of theme)")] = None,
    pages: Annotated[Optional[str], Field(description="Comma list of page numbers to print (blank = all pages)")] = None,
) -> dict[str, Any]:
    """Export a schematic to SVG via kicad-cli (`sch export svg`), one SVG per page into a directory. Exposes drawing-sheet override, theme, black-and-white, exclude-drawing-sheet, default-font, no-background-color, and page selection. schematicPath is REQUIRED."""
    return dispatch_command("export_sch_svg", {"schematicPath": schematicPath, "outputDir": outputDir, "drawingSheet": drawingSheet, "defineVar": defineVar, "theme": theme, "blackAndWhite": blackAndWhite, "excludeDrawingSheet": excludeDrawingSheet, "defaultFont": defaultFont, "noBackgroundColor": noBackgroundColor, "pages": pages})


def export_svg(
    outputPath: Annotated[str, Field(description="Path to save the SVG file")],
    layers: Annotated[Optional[List[str]], Field(description="Optional array of layer names to include (default: all)")] = None,
    blackAndWhite: Annotated[Optional[bool], Field(description="Whether to export in black and white")] = None,
    includeComponents: Annotated[Optional[bool], Field(description="Whether to include component outlines")] = None,
) -> dict[str, Any]:
    """Export the PCB layout as an SVG vector image, optionally selecting layers and colour mode."""
    return dispatch_command("export_svg", {"outputPath": outputPath, "layers": layers, "blackAndWhite": blackAndWhite, "includeComponents": includeComponents})


def export_vrml(
    outputPath: Annotated[str, Field(description="Path to save the VRML file")],
    includeComponents: Annotated[Optional[bool], Field(description="Whether to include 3D component models")] = None,
    useRelativePaths: Annotated[Optional[bool], Field(description="Whether to use relative paths for 3D models")] = None,
) -> dict[str, Any]:
    """Export the PCB as a VRML 3D model for use in web viewers or simulation tools."""
    return dispatch_command("export_vrml", {"outputPath": outputPath, "includeComponents": includeComponents, "useRelativePaths": useRelativePaths})


_TOOLS = [
    export_3d,
    export_3d_cli,
    export_bom,
    export_drill,
    export_gencad,
    export_gerber,
    export_gerber_single,
    export_gerbers,
    export_ipc2581,
    export_ipcd356,
    export_netlist,
    export_odb,
    export_pcb_dxf,
    export_pcb_pdf,
    export_pcb_svg,
    export_pdf,
    export_pos,
    export_position_file,
    export_sch_bom,
    export_sch_dxf,
    export_sch_hpgl,
    export_sch_pdf,
    export_sch_ps,
    export_sch_python_bom,
    export_sch_svg,
    export_svg,
    export_vrml,
]


def register(mcp: Any) -> None:
    for fn in _TOOLS:
        mcp.tool()(fn)
