"""footprint toolset — GENERATED by scripts/gen_toolsets.py, do not hand-edit.

Source of truth: tests/fixtures/tools_baseline.json (module "footprint").
"""

from __future__ import annotations

from typing import Annotated, Any, Dict, List, Literal, Optional, Union

from pydantic import BaseModel, Field

from kicad_mcp.toolsets._common import dispatch_command

class AddComponent3dModelOffset(BaseModel):
    """Model offset in mm (default 0,0,0)"""

    x: float
    y: float
    z: float


class AddComponent3dModelScale(BaseModel):
    """Model scale factor (default 1,1,1)"""

    x: float
    y: float
    z: float


class AddComponent3dModelRotate(BaseModel):
    """Model rotation in degrees (default 0,0,0)"""

    x: float
    y: float
    z: float


class AddFootprint3dModelOffset(BaseModel):
    """Model offset in mm (default 0,0,0)"""

    x: float
    y: float
    z: float


class AddFootprint3dModelScale(BaseModel):
    """Model scale factor (default 1,1,1)"""

    x: float
    y: float
    z: float


class AddFootprint3dModelRotate(BaseModel):
    """Model rotation in degrees (default 0,0,0)"""

    x: float
    y: float
    z: float


class CreateFootprintPadsItemAt(BaseModel):
    """Pad centre position"""

    x: Annotated[float, Field(description="X position in mm")]
    y: Annotated[float, Field(description="Y position in mm")]
    angle: Annotated[Optional[float], Field(description="Rotation angle in degrees (default 0)")] = None


class CreateFootprintPadsItemSize(BaseModel):
    """Pad size in mm"""

    w: Annotated[float, Field(description="Width in mm")]
    h: Annotated[float, Field(description="Height in mm")]


class CreateFootprintPadsItem(BaseModel):
    number: Annotated[str, Field(description="Pad number / name, e.g. '1', '2', 'A1'")]
    type: Annotated[Literal["smd", "thru_hole", "np_thru_hole"], Field(description="Pad type: smd | thru_hole | np_thru_hole")]
    shape: Annotated[Optional[Literal["rect", "circle", "oval", "roundrect"]], Field(description="Pad shape (default: rect for SMD, circle for THT)")] = None
    at: Annotated[CreateFootprintPadsItemAt, Field(description="Pad centre position")]
    size: Annotated[CreateFootprintPadsItemSize, Field(description="Pad size in mm")]
    drill: Annotated[Optional[Any], Field(description="Drill size (required for thru_hole pads)")] = None
    layers: Annotated[Optional[List[str]], Field(description="Override default layer list, e.g. ['F.Cu','F.Paste','F.Mask']")] = None
    roundrect_ratio: Annotated[Optional[float], Field(description="Corner radius ratio for roundrect shape (0.0\u20130.5, default 0.25)", ge=0, le=0.5)] = None


class CreateFootprintCourtyard(BaseModel):
    """Courtyard rectangle on F.CrtYd (recommended: 0.25 mm clearance around pads)"""

    x1: Annotated[float, Field(description="Left X in mm")]
    y1: Annotated[float, Field(description="Top Y in mm")]
    x2: Annotated[float, Field(description="Right X in mm")]
    y2: Annotated[float, Field(description="Bottom Y in mm")]
    width: Annotated[Optional[float], Field(description="Line width in mm")] = None


class CreateFootprintSilkscreen(BaseModel):
    """Silkscreen rectangle on F.SilkS"""

    x1: Annotated[float, Field(description="Left X in mm")]
    y1: Annotated[float, Field(description="Top Y in mm")]
    x2: Annotated[float, Field(description="Right X in mm")]
    y2: Annotated[float, Field(description="Bottom Y in mm")]
    width: Annotated[Optional[float], Field(description="Line width in mm")] = None


class CreateFootprintFablayer(BaseModel):
    """Fab-layer rectangle on F.Fab (shows component body)"""

    x1: Annotated[float, Field(description="Left X in mm")]
    y1: Annotated[float, Field(description="Top Y in mm")]
    x2: Annotated[float, Field(description="Right X in mm")]
    y2: Annotated[float, Field(description="Bottom Y in mm")]
    width: Annotated[Optional[float], Field(description="Line width in mm")] = None


class CreateFootprintRefposition(BaseModel):
    """Position of the REF** text (default: 0, -1.27)"""

    x: float
    y: float


class CreateFootprintValueposition(BaseModel):
    """Position of the Value text (default: 0, 1.27)"""

    x: float
    y: float


class EditFootprintPadSize(BaseModel):
    """New pad size in mm"""

    w: Annotated[float, Field(description="Width in mm")]
    h: Annotated[float, Field(description="Height in mm")]


class EditFootprintPadAt(BaseModel):
    """New pad position in mm"""

    x: Annotated[float, Field(description="X position in mm")]
    y: Annotated[float, Field(description="Y position in mm")]
    angle: Annotated[Optional[float], Field(description="Rotation angle in degrees (default 0)")] = None

def add_component_3d_model(
    reference: Annotated[Any, Field(description="Footprint reference(s), e.g. 'D1', ['D1','D2'], or '*' for all footprints")],
    modelPath: Annotated[str, Field(description="Path to the 3D model, e.g. ${KIPRJMOD}/MyProj.3dshapes/MyPart.step")],
    offset: Annotated[Optional[AddComponent3dModelOffset], Field(description="Model offset in mm (default 0,0,0)")] = None,
    scale: Annotated[Optional[AddComponent3dModelScale], Field(description="Model scale factor (default 1,1,1)")] = None,
    rotate: Annotated[Optional[AddComponent3dModelRotate], Field(description="Model rotation in degrees (default 0,0,0)")] = None,
    replace: Annotated[Optional[bool], Field(description="Replace an existing model with the same filename (default true)")] = None,
) -> dict[str, Any]:
    """Attach a 3D model to one or more PLACED footprints on the open board, live via the KiCAD IPC API (changes appear instantly, no file conflicts). Use this for components already on the PCB; for a library .kicad_mod use add_footprint_3d_model."""
    return dispatch_command("add_component_3d_model", {"reference": reference, "modelPath": modelPath, "offset": offset, "scale": scale, "rotate": rotate, "replace": replace})


def add_footprint_3d_model(
    footprintPath: Annotated[str, Field(description="Full path to the .kicad_mod file, e.g. C:/MyLib.pretty/MyPart.kicad_mod")],
    modelPath: Annotated[str, Field(description="Path to the 3D model file. Prefer ${KIPRJMOD}/MyProj.3dshapes/MyPart.step for portability.")],
    offset: Annotated[Optional[AddFootprint3dModelOffset], Field(description="Model offset in mm (default 0,0,0)")] = None,
    scale: Annotated[Optional[AddFootprint3dModelScale], Field(description="Model scale factor (default 1,1,1)")] = None,
    rotate: Annotated[Optional[AddFootprint3dModelRotate], Field(description="Model rotation in degrees (default 0,0,0)")] = None,
    replace: Annotated[Optional[bool], Field(description="Replace an existing model with the same filename (default true)")] = None,
) -> dict[str, Any]:
    """Attach (or replace) a 3D model — .step/.stp/.wrl — to a .kicad_mod footprint file. KiCAD path variables like ${KIPRJMOD} or ${KICAD10_3DMODEL_DIR} are supported. Use this after create_footprint so the part shows up in the 3D viewer (Alt+3)."""
    return dispatch_command("add_footprint_3d_model", {"footprintPath": footprintPath, "modelPath": modelPath, "offset": offset, "scale": scale, "rotate": rotate, "replace": replace})


def create_footprint(
    libraryPath: Annotated[str, Field(description="Path to the .pretty library directory (created if missing). E.g. C:/MyProject/MyLib.pretty")],
    name: Annotated[str, Field(description="Footprint name, e.g. 'R_0603_Custom'")],
    description: Annotated[Optional[str], Field(description="Human-readable description")] = None,
    tags: Annotated[Optional[str], Field(description="Space-separated tag string, e.g. 'resistor SMD 0603'")] = None,
    pads: Annotated[Optional[List[CreateFootprintPadsItem]], Field(description="List of pads to add (can be empty for outlines-only footprints)")] = None,
    courtyard: Annotated[Optional[CreateFootprintCourtyard], Field(description="Courtyard rectangle on F.CrtYd (recommended: 0.25 mm clearance around pads)")] = None,
    silkscreen: Annotated[Optional[CreateFootprintSilkscreen], Field(description="Silkscreen rectangle on F.SilkS")] = None,
    fabLayer: Annotated[Optional[CreateFootprintFablayer], Field(description="Fab-layer rectangle on F.Fab (shows component body)")] = None,
    refPosition: Annotated[Optional[CreateFootprintRefposition], Field(description="Position of the REF** text (default: 0, -1.27)")] = None,
    valuePosition: Annotated[Optional[CreateFootprintValueposition], Field(description="Position of the Value text (default: 0, 1.27)")] = None,
    overwrite: Annotated[Optional[bool], Field(description="Replace existing footprint file (default: false)")] = None,
) -> dict[str, Any]:
    """Create a new KiCAD footprint (.kicad_mod) inside a .pretty library directory. Supports SMD and THT pads, courtyard, silkscreen, and fab-layer rectangles."""
    return dispatch_command("create_footprint", {"libraryPath": libraryPath, "name": name, "description": description, "tags": tags, "pads": pads, "courtyard": courtyard, "silkscreen": silkscreen, "fabLayer": fabLayer, "refPosition": refPosition, "valuePosition": valuePosition, "overwrite": overwrite})


def edit_footprint_pad(
    footprintPath: Annotated[str, Field(description="Full path to the .kicad_mod file, e.g. C:/MyLib.pretty/R_Custom.kicad_mod")],
    padNumber: Annotated[Union[str, float], Field(description="Pad number to edit, e.g. '1' or 2")],
    size: Annotated[Optional[EditFootprintPadSize], Field(description="New pad size in mm")] = None,
    at: Annotated[Optional[EditFootprintPadAt], Field(description="New pad position in mm")] = None,
    drill: Annotated[Optional[Any], Field(description="New drill size (for THT pads)")] = None,
    shape: Annotated[Optional[Literal["rect", "circle", "oval", "roundrect"]], Field(description="New pad shape")] = None,
) -> dict[str, Any]:
    """Edit an existing pad inside a .kicad_mod footprint file. Updates size, position, drill, or shape without recreating the whole footprint."""
    return dispatch_command("edit_footprint_pad", {"footprintPath": footprintPath, "padNumber": padNumber, "size": size, "at": at, "drill": drill, "shape": shape})


def import_3d_model(
    modelPath: Annotated[str, Field(description="Path to the source 3D model file to import")],
    projectPath: Annotated[str, Field(description="Path to the .kicad_pro file or the project directory (used to locate the .3dshapes folder and compute ${KIPRJMOD})")],
    libraryDir: Annotated[Optional[str], Field(description="Target *.3dshapes directory (absolute, or relative to the project). Default: <project>/<project>.3dshapes")] = None,
    newName: Annotated[Optional[str], Field(description="Rename the copied file (source extension kept if omitted)")] = None,
    overwrite: Annotated[Optional[bool], Field(description="Overwrite an existing destination file (default false)")] = None,
) -> dict[str, Any]:
    """Copy a 3D model file (.step/.stp/.wrl/.x3d/.iges) into the project's *.3dshapes library folder and return a portable ${KIPRJMOD}/... path. Feed the returned 'modelPath' straight into add_footprint_3d_model or add_component_3d_model."""
    return dispatch_command("import_3d_model", {"modelPath": modelPath, "projectPath": projectPath, "libraryDir": libraryDir, "newName": newName, "overwrite": overwrite})


def list_footprint_libraries(
    searchPaths: Annotated[Optional[List[str]], Field(description="Override default search paths. Each entry should be a directory that contains .pretty subdirs.")] = None,
) -> dict[str, Any]:
    """List available .pretty footprint libraries and their contents (first 20 footprints per library). Searches KiCAD standard install paths by default."""
    return dispatch_command("list_footprint_libraries", {"searchPaths": searchPaths})


def register_footprint_library(
    libraryPath: Annotated[str, Field(description="Full path to the .pretty directory to register")],
    libraryName: Annotated[Optional[str], Field(description="Nickname for the library in KiCAD (default: directory name without .pretty)")] = None,
    description: Annotated[Optional[str], Field(description="Optional description")] = None,
    scope: Annotated[Optional[Literal["project", "global"]], Field(description="project = writes fp-lib-table next to the .kicad_pro file (default); global = writes to the user's global KiCAD config")] = None,
    projectPath: Annotated[Optional[str], Field(description="Path to the .kicad_pro file or its directory (required for scope=project when the library is not in the project folder)")] = None,
) -> dict[str, Any]:
    """Register a .pretty footprint library in KiCAD's fp-lib-table so KiCAD can find the footprints. Run this after create_footprint when KiCAD shows 'library not found in footprint library table'."""
    return dispatch_command("register_footprint_library", {"libraryPath": libraryPath, "libraryName": libraryName, "description": description, "scope": scope, "projectPath": projectPath})


_TOOLS = [
    add_component_3d_model,
    add_footprint_3d_model,
    create_footprint,
    edit_footprint_pad,
    import_3d_model,
    list_footprint_libraries,
    register_footprint_library,
]


def register(mcp: Any) -> None:
    for fn in _TOOLS:
        mcp.tool()(fn)
