"""freerouting toolset — GENERATED by scripts/gen_toolsets.py, do not hand-edit.

Source of truth: tests/fixtures/tools_baseline.json (module "freerouting").
"""

from __future__ import annotations

from typing import Annotated, Any, Dict, List, Literal, Optional, Union

from pydantic import BaseModel, Field

from kicad_mcp.toolsets._common import dispatch_command

def autoroute(
    boardPath: Annotated[Optional[str], Field(description="Path to .kicad_pcb file (default: current board)")] = None,
    freeroutingJar: Annotated[Optional[str], Field(description="Path to freerouting.jar (default: ~/.kicad-mcp/freerouting.jar or FREEROUTING_JAR env)")] = None,
    maxPasses: Annotated[Optional[float], Field(description="Maximum routing passes for single-attempt mode (default: 20). Ignored when `attempts` > 1; use `passSchedule` instead.")] = None,
    timeout: Annotated[Optional[float], Field(description="Per-attempt timeout in seconds (default: 300)")] = None,
    attempts: Annotated[Optional[int], Field(description="Number of Freerouting runs to try (default: 1 \u2014 backward-compatible). When > 1, runs best-of-N: scores each attempt by routing completeness and keeps the SES with the highest score. Recommended: 3\u20135 for dense boards.", ge=1)] = None,
    targetNets: Annotated[Optional[List[str]], Field(description="Optional list of critical net names. An attempt that routes all of them earns a 50,000-point scoring bonus, breaking ties in favour of designs that include the must-have nets.")] = None,
    passSchedule: Annotated[Optional[List[float]], Field(description="Per-attempt `--max-passes` values to cycle through (default: [50, 60, 65, 70, 75, 80, 85, 90, 55, 95]). The list wraps if `attempts` exceeds its length.")] = None,
) -> dict[str, Any]:
    """Run Freerouting autorouter on the current PCB. Exports to Specctra DSN, runs Freerouting CLI, and imports the routed SES result. Requires Java 11+ and freerouting.jar (see check_freerouting). Set `attempts` > 1 to run best-of-N: Freerouting is invoked multiple times with varied `--max-passes`, each result is scored by (nets_routed * 1000 + segments, +50000 bonus when every `targetNets` entry routed), and the winning SES is imported. Single-attempt behaviour is unchanged when `attempts` is omitted."""
    return dispatch_command("autoroute", {"boardPath": boardPath, "freeroutingJar": freeroutingJar, "maxPasses": maxPasses, "timeout": timeout, "attempts": attempts, "targetNets": targetNets, "passSchedule": passSchedule})


def check_freerouting(
    freeroutingJar: Annotated[Optional[str], Field(description="Path to freerouting.jar to check")] = None,
) -> dict[str, Any]:
    """Check if Java and Freerouting JAR are available on the system. Run this before autoroute to verify prerequisites."""
    return dispatch_command("check_freerouting", {"freeroutingJar": freeroutingJar})


def export_dsn(
    boardPath: Annotated[Optional[str], Field(description="Path to .kicad_pcb file (default: current board)")] = None,
    outputPath: Annotated[Optional[str], Field(description="Output DSN file path (default: same dir as board)")] = None,
) -> dict[str, Any]:
    """Export the current PCB to Specctra DSN format. Useful for manual Freerouting workflow or external autorouters."""
    return dispatch_command("export_dsn", {"boardPath": boardPath, "outputPath": outputPath})


def import_ses(
    sesPath: Annotated[str, Field(description="Path to the .ses file to import")],
    boardPath: Annotated[Optional[str], Field(description="Path to .kicad_pcb file (default: current board)")] = None,
) -> dict[str, Any]:
    """Import a Specctra SES (session) file into the current PCB. Use after running Freerouting externally."""
    return dispatch_command("import_ses", {"sesPath": sesPath, "boardPath": boardPath})


_TOOLS = [
    autoroute,
    check_freerouting,
    export_dsn,
    import_ses,
]


def register(mcp: Any) -> None:
    for fn in _TOOLS:
        mcp.tool()(fn)
