"""jlcpcb-api toolset — GENERATED by scripts/gen_toolsets.py, do not hand-edit.

Source of truth: tests/fixtures/tools_baseline.json (module "jlcpcb-api").
"""

from __future__ import annotations

from typing import Annotated, Any, Dict, List, Literal, Optional, Union

from pydantic import BaseModel, Field

from kicad_mcp.toolsets._common import dispatch_command

def download_jlcpcb_database(
    force: Annotated[bool, Field(description="Force re-download even if database exists")] = False,
    source: Annotated[Optional[Literal["cdfer", "yaqwsx", "official"]], Field(description="Force one source. \"cdfer\" (default) = in-stock subset, no 7z needed. \"yaqwsx\" = FULL ~10GB catalog (needs a 7z CLI). \"official\" = JLCPCB API (needs creds).")] = None,
) -> dict[str, Any]:
    """Download the JLCPCB parts catalog to a local SQLite database for fast offline search.

Sources (no API credentials required by default):
  - cdfer (default): in-stock subset (~600k parts, ~1.5 GB download). Single file,
    no extra tools — the most reliable path, especially on Windows.
  - yaqwsx: the FULL catalog (all parts incl. out-of-stock, ~10 GB extracted).
    Use source="yaqwsx" if you specifically want everything. Requires a 7z CLI.
  - official: official JLCPCB API, used only if JLCPCB_APP_ID/JLCPCB_API_KEY/
    JLCPCB_API_SECRET are set.

One-time setup; downloads resume automatically if interrupted. Re-run with
force=true to refresh."""
    return dispatch_command("download_jlcpcb_database", {"force": force, "source": source})


def get_jlcpcb_database_stats() -> dict[str, Any]:
    """Get statistics about the local JLCPCB parts database"""
    return dispatch_command("get_jlcpcb_database_stats", {})


def get_jlcpcb_part(
    lcsc_number: Annotated[str, Field(description="LCSC part number (e.g., 'C25804', 'C2286')")],
) -> dict[str, Any]:
    """Get detailed information about a specific JLCPCB part by LCSC number"""
    return dispatch_command("get_jlcpcb_part", {"lcsc_number": lcsc_number})


def search_jlcpcb_parts(
    query: Annotated[Optional[str], Field(description="Free-text search (e.g., '10k resistor 0603', 'ESP32', 'STM32F103')")] = None,
    category: Annotated[Optional[str], Field(description="Filter by category (e.g., 'Resistors', 'Capacitors', 'Microcontrollers')")] = None,
    package: Annotated[Optional[str], Field(description="Filter by package type (e.g., '0603', 'SOT-23', 'QFN-32')")] = None,
    library_type: Annotated[Literal["Basic", "Extended", "Preferred", "All"], Field(description="Filter by library type (Basic = free assembly at JLCPCB)")] = 'All',
    manufacturer: Annotated[Optional[str], Field(description="Filter by manufacturer name")] = None,
    in_stock: Annotated[bool, Field(description="Only show parts with available stock")] = True,
    limit: Annotated[float, Field(description="Maximum number of results to return")] = 20,
) -> dict[str, Any]:
    """Search JLCPCB parts catalog by specifications.

Searches the local JLCPCB database (must be downloaded first with download_jlcpcb_database).
Provides real pricing, stock info, and library type (Basic parts = free assembly).

Use this to find components with exact specifications and cost optimization."""
    return dispatch_command("search_jlcpcb_parts", {"query": query, "category": category, "package": package, "library_type": library_type, "manufacturer": manufacturer, "in_stock": in_stock, "limit": limit})


def suggest_jlcpcb_alternatives(
    lcsc_number: Annotated[str, Field(description="Reference LCSC part number to find alternatives for")],
    limit: Annotated[float, Field(description="Maximum number of alternatives to return")] = 5,
) -> dict[str, Any]:
    """Suggest alternative JLCPCB parts for a given component.

Finds similar parts that may be cheaper, have more stock, or are Basic library type.
Useful for cost optimization and finding alternatives when parts are out of stock."""
    return dispatch_command("suggest_jlcpcb_alternatives", {"lcsc_number": lcsc_number, "limit": limit})


_TOOLS = [
    download_jlcpcb_database,
    get_jlcpcb_database_stats,
    get_jlcpcb_part,
    search_jlcpcb_parts,
    suggest_jlcpcb_alternatives,
]


def register(mcp: Any) -> None:
    for fn in _TOOLS:
        mcp.tool()(fn)
