"""library toolset — GENERATED by scripts/gen_toolsets.py, do not hand-edit.

Source of truth: tests/fixtures/tools_baseline.json (module "library").
"""

from __future__ import annotations

from typing import Annotated, Any, Dict, List, Literal, Optional, Union

from pydantic import BaseModel, Field

from kicad_mcp.toolsets._common import dispatch_command

def get_footprint_info(
    library_name: Annotated[str, Field(description="Name of the library containing the footprint")],
    footprint_name: Annotated[str, Field(description="Name of the footprint to get information about")],
) -> dict[str, Any]:
    """Get detailed information about a specific footprint"""
    return dispatch_command("get_footprint_info", {"library_name": library_name, "footprint_name": footprint_name})


def list_libraries(
    search_paths: Annotated[Optional[List[str]], Field(description="Optional additional search paths for libraries")] = None,
) -> dict[str, Any]:
    """List all available KiCAD footprint libraries"""
    return dispatch_command("list_libraries", {"search_paths": search_paths})


def list_library_footprints(
    library_name: Annotated[str, Field(description="Name of the library to list footprints from")],
    filter: Annotated[Optional[str], Field(description="Optional filter pattern for footprint names")] = None,
    limit: Annotated[float, Field(description="Maximum number of footprints to list")] = 100,
) -> dict[str, Any]:
    """List all footprints in a specific KiCAD library"""
    return dispatch_command("list_library_footprints", {"library_name": library_name, "filter": filter, "limit": limit})


def search_footprints(
    search_term: Annotated[str, Field(description="Search term or pattern to match footprint names")],
    library: Annotated[Optional[str], Field(description="Optional specific library to search in")] = None,
    limit: Annotated[float, Field(description="Maximum number of results to return")] = 50,
) -> dict[str, Any]:
    """Search for footprints matching a pattern across all libraries"""
    return dispatch_command("search_footprints", {"search_term": search_term, "library": library, "limit": limit})


_TOOLS = [
    get_footprint_info,
    list_libraries,
    list_library_footprints,
    search_footprints,
]


def register(mcp: Any) -> None:
    for fn in _TOOLS:
        mcp.tool()(fn)
