"""library-symbol toolset — GENERATED by scripts/gen_toolsets.py, do not hand-edit.

Source of truth: tests/fixtures/tools_baseline.json (module "library-symbol").
"""

from __future__ import annotations

from typing import Annotated, Any, Dict, List, Literal, Optional, Union

from pydantic import BaseModel, Field

from kicad_mcp.toolsets._common import dispatch_command

def batch_list_symbol_pins(
    symbols: Annotated[List[str], Field(description="Array of symbols in 'Library:SymbolName' format (e.g., ['Device:R', 'Device:C'])")],
    schematicPath: Annotated[Optional[str], Field(description="Path to .kicad_sch \u2014 enables project-local sym-lib-table lookup")] = None,
    compact: Annotated[Optional[bool], Field(description="If true, omit per-pin detail for standard 2-pin symmetric passives.")] = None,
) -> dict[str, Any]:
    """Return pin names, numbers, types, and symbol-local coordinates for multiple symbols in a single call. Use instead of calling list_symbol_pins repeatedly when placing a subcircuit — saves 5–10 round-trips. Each result includes pins (with x/y/angle in symbol-local coords, Y-up per KiCAD lib convention) and body_bbox (bounding box of pin envelope ±1.27mm, symbol-local coords). IMPORTANT: coordinates are symbol-local (Y-up, pre-rotation); after placement use get_schematic_pin_locations for post-rotation schematic coordinates. Set compact=true for simple 2-pin passives (Device:R/C/L) to get just pin_count, body_bbox, and is_symmetric."""
    return dispatch_command("batch_list_symbol_pins", {"symbols": symbols, "schematicPath": schematicPath, "compact": compact})


def get_symbol_info(
    symbol: Annotated[str, Field(description="Symbol specification (e.g., 'Device:R' or 'PCM_JLCPCB-MCUs:STM32F103C8T6')")],
    projectPath: Annotated[Optional[str], Field(description="Optional: project directory or .kicad_pro/.kicad_pcb/.kicad_sch path so project-scope libraries are searched.")] = None,
) -> dict[str, Any]:
    """Get detailed information about a specific symbol (global or project-scope when projectPath is supplied or a project has been opened)."""
    return dispatch_command("get_symbol_info", {"symbol": symbol, "projectPath": projectPath})


def list_library_symbols(
    library: Annotated[str, Field(description="Library name (e.g., 'Device', 'PCM_JLCPCB-MCUs')")],
    projectPath: Annotated[Optional[str], Field(description="Optional: project directory or .kicad_pro/.kicad_pcb/.kicad_sch path to resolve project-scope libraries.")] = None,
) -> dict[str, Any]:
    """List all symbols in a specific KiCAD symbol library (global or project-scope when projectPath is supplied or a project has been opened)."""
    return dispatch_command("list_library_symbols", {"library": library, "projectPath": projectPath})


def list_symbol_libraries(
    projectPath: Annotated[Optional[str], Field(description="Optional: project directory or .kicad_pro/.kicad_pcb/.kicad_sch path. Including this exposes project-scope sym-lib-table libraries.")] = None,
) -> dict[str, Any]:
    """List all available KiCAD symbol libraries from global sym-lib-table, plus the project's sym-lib-table when projectPath (or any related file) is supplied or a project has been opened."""
    return dispatch_command("list_symbol_libraries", {"projectPath": projectPath})


def list_symbol_pins(
    symbol: Annotated[str, Field(description="Symbol in 'Library:SymbolName' format (e.g., Device:R, Connector:Conn_01x04)")],
    schematicPath: Annotated[Optional[str], Field(description="Path to .kicad_sch \u2014 enables project-local sym-lib-table lookup")] = None,
) -> dict[str, Any]:
    """Return pin names, numbers, and types for a symbol directly from the library — no schematic required. Use this before add_schematic_component to discover pins for connect_to_net calls. Each pin has 'number' (e.g. '1', 'A5') and 'name' (e.g. 'FB', 'GND') — connect_to_net accepts either. Pass schematicPath to resolve project-local symbols. Returns close-match suggestions if the symbol name is slightly wrong."""
    return dispatch_command("list_symbol_pins", {"symbol": symbol, "schematicPath": schematicPath})


def search_symbols(
    query: Annotated[str, Field(description="Search query (e.g., 'ESP32', 'STM32F103', 'C8734' for LCSC ID)")],
    library: Annotated[Optional[str], Field(description="Optional: filter to specific library name pattern (e.g., 'JLCPCB')")] = None,
    limit: Annotated[float, Field(description="Maximum number of results to return")] = 20,
    projectPath: Annotated[Optional[str], Field(description="Optional: project directory or .kicad_pro/.kicad_pcb/.kicad_sch path so project-scope sym-lib-table libraries are searched too.")] = None,
) -> dict[str, Any]:
    """Search for symbols in local KiCAD symbol libraries.

Searches by: symbol name, LCSC ID, description, manufacturer, MPN, category.
Use this to find components already in your local libraries (e.g., JLCPCB-KiCad-Library).

Returns symbol references that can be used directly in schematics."""
    return dispatch_command("search_symbols", {"query": query, "library": library, "limit": limit, "projectPath": projectPath})


_TOOLS = [
    batch_list_symbol_pins,
    get_symbol_info,
    list_library_symbols,
    list_symbol_libraries,
    list_symbol_pins,
    search_symbols,
]


def register(mcp: Any) -> None:
    for fn in _TOOLS:
        mcp.tool()(fn)
