"""project toolset — GENERATED by scripts/gen_toolsets.py, do not hand-edit.

Source of truth: tests/fixtures/tools_baseline.json (module "project").
"""

from __future__ import annotations

from typing import Annotated, Any, Dict, List, Literal, Optional, Union

from pydantic import BaseModel, Field

from kicad_mcp.toolsets._common import dispatch_command

def close_project(
    save: Annotated[Optional[bool], Field(description="Save the board to disk before closing (default true). If false and there are unsaved changes, the close proceeds but the response warns they were discarded.")] = None,
) -> dict[str, Any]:
    """Close the currently loaded KiCAD project: optionally save, then drop the in-memory board and clear session state. Use this to hand control back so the user (or the agent) can edit project files directly without the MCP later clobbering those changes on save."""
    return dispatch_command("close_project", {"save": save})


def create_project(
    path: Annotated[str, Field(description="Project directory path")],
    name: Annotated[str, Field(description="Project name")],
) -> dict[str, Any]:
    """Create a new KiCAD project"""
    return dispatch_command("create_project", {"path": path, "name": name})


def get_project_info() -> dict[str, Any]:
    """Get information about the current KiCAD project"""
    return dispatch_command("get_project_info", {})


def open_project(
    filename: Annotated[str, Field(description="Path to .kicad_pro or .kicad_pcb file")],
) -> dict[str, Any]:
    """Open an existing KiCAD project"""
    return dispatch_command("open_project", {"filename": filename})


def save_project(
    path: Annotated[Optional[str], Field(description="Optional new path to save to")] = None,
    force: Annotated[Optional[bool], Field(description="Overwrite the loaded board file even if its on-disk contents changed externally")] = None,
) -> dict[str, Any]:
    """Save the current KiCAD project. Refuses to overwrite the board file if its contents changed on disk since load (external edit) unless force is true."""
    return dispatch_command("save_project", {"path": path, "force": force})


def snapshot_project(
    step: Annotated[str, Field(description="Step number or identifier, e.g. '1' or '2'")],
    label: Annotated[str, Field(description="Short label for this checkpoint, e.g. 'schematic_ok' or 'layout_ok'")],
    prompt: Annotated[Optional[str], Field(description="Full prompt text to save as PROMPT_step{step}_{timestamp}.md alongside the snapshot")] = None,
) -> dict[str, Any]:
    """Save a named checkpoint snapshot of the current project state (renders board to PDF and records step label). Call after completing each major step — e.g. after Step 1 (schematic_ok) and Step 2 (layout_ok). Required by the demo workflow before waiting for user confirmation."""
    return dispatch_command("snapshot_project", {"step": step, "label": label, "prompt": prompt})


_TOOLS = [
    close_project,
    create_project,
    get_project_info,
    open_project,
    save_project,
    snapshot_project,
]


def register(mcp: Any) -> None:
    for fn in _TOOLS:
        mcp.tool()(fn)
