"""routing toolset — GENERATED by scripts/gen_toolsets.py, do not hand-edit.

Source of truth: tests/fixtures/tools_baseline.json (module "routing").
"""

from __future__ import annotations

from typing import Annotated, Any, Dict, List, Literal, Optional, Union

from pydantic import BaseModel, Field

from kicad_mcp.toolsets._common import dispatch_command

class AddCopperPourOutlineItem(BaseModel):
    x: float
    y: float


class AddViaPosition(BaseModel):
    """Via position"""

    x: float
    y: float
    unit: Optional[str] = None


class DeleteTracePosition(BaseModel):
    """Delete trace nearest to this position"""

    x: float
    y: float
    unit: Optional[Literal["mm", "inch", "mil"]] = None


class QueryTracesBoundingbox(BaseModel):
    """Filter by bounding box region"""

    x1: float
    y1: float
    x2: float
    y2: float
    unit: Optional[Literal["mm", "inch", "mil"]] = None


class QueryZonesBoundingbox(BaseModel):
    """Filter to zones whose bounding box overlaps this region"""

    x1: float
    y1: float
    x2: float
    y2: float
    unit: Optional[Literal["mm", "inch"]] = None


class RouteArcTraceStart(BaseModel):
    """Arc start position"""

    x: float
    y: float
    unit: Optional[str] = None


class RouteArcTraceMid(BaseModel):
    """A point on arc midpoint"""

    x: float
    y: float
    unit: Optional[str] = None


class RouteArcTraceEnd(BaseModel):
    """Arc end position"""

    x: float
    y: float
    unit: Optional[str] = None


class RouteDifferentialPairPositivepad(BaseModel):
    """Positive pad (component and pad number)"""

    reference: str
    pad: str


class RouteDifferentialPairNegativepad(BaseModel):
    """Negative pad (component and pad number)"""

    reference: str
    pad: str


class RouteTraceStart(BaseModel):
    """Start position"""

    x: float
    y: float
    unit: Optional[str] = None


class RouteTraceEnd(BaseModel):
    """End position"""

    x: float
    y: float
    unit: Optional[str] = None

def add_copper_pour(
    layer: Annotated[str, Field(description="PCB layer")],
    net: Annotated[str, Field(description="Net name")],
    clearance: Annotated[Optional[float], Field(description="Clearance in mm")] = None,
    outline: Annotated[Optional[List[AddCopperPourOutlineItem]], Field(description="Array of {x, y} points defining the pour boundary. If omitted, the board outline is used.")] = None,
) -> dict[str, Any]:
    """Add a copper pour (ground/power plane) to the PCB"""
    return dispatch_command("add_copper_pour", {"layer": layer, "net": net, "clearance": clearance, "outline": outline})


def add_gnd_stitching_vias(
    gndNet: Annotated[Optional[str], Field(description="Name of the ground net (default: auto-detect GND / GROUND / VSS / /GND).")] = None,
    strategies: Annotated[Optional[List[Literal["grid", "around_refs", "in_zones"]]], Field(description="Which placement strategies to combine (default: ['grid']). Pass ['grid', 'around_refs', 'in_zones'] for full coverage.")] = None,
    viaSize: Annotated[Optional[float], Field(description="Via pad diameter in mm (default 0.6).")] = None,
    viaDrill: Annotated[Optional[float], Field(description="Via drill diameter in mm (default 0.3). Must be smaller than viaSize.")] = None,
    clearance: Annotated[Optional[float], Field(description="Extra clearance beyond required between each new via and existing copper, in mm (default 0.2).")] = None,
    spacing: Annotated[Optional[float], Field(description="Grid spacing in mm for `grid` and `around_refs` strategies (default 5.0).")] = None,
    densifyRefs: Annotated[Optional[List[str]], Field(description="Reference designators to densify ground around (used by `around_refs`). Targets: MCUs, switching regulators, RF parts.")] = None,
    densifyRadius: Annotated[Optional[int], Field(description="How many grid cells around each ref to try (default 2 = 5x5 candidate field per ref).")] = None,
    edgeMargin: Annotated[Optional[float], Field(description="Keep-out from the board edge in mm (default 0.5).")] = None,
    maxVias: Annotated[Optional[int], Field(description="Cap on total placements across all strategies (default unlimited).")] = None,
    dryRun: Annotated[Optional[bool], Field(description="If true, return the placements that would be made but don't modify the board (default false).")] = None,
) -> dict[str, Any]:
    """Drop GND stitching vias across the board with collision checking against every non-GND segment, via, and pad on every copper layer (PTH vias penetrate the full stackup, so missing any one layer is the classic silent-short failure mode). Three combinable strategies: `grid` (regular grid across the interior), `around_refs` (densify around named ICs), and `in_zones` (only place vias inside an actual GND copper zone). Supports `dryRun` to preview placements without writing."""
    return dispatch_command("add_gnd_stitching_vias", {"gndNet": gndNet, "strategies": strategies, "viaSize": viaSize, "viaDrill": viaDrill, "clearance": clearance, "spacing": spacing, "densifyRefs": densifyRefs, "densifyRadius": densifyRadius, "edgeMargin": edgeMargin, "maxVias": maxVias, "dryRun": dryRun})


def add_net(
    name: Annotated[str, Field(description="Net name")],
    netClass: Annotated[Optional[str], Field(description="Net class name")] = None,
) -> dict[str, Any]:
    """Create a new net on the PCB"""
    return dispatch_command("add_net", {"name": name, "netClass": netClass})


def add_via(
    position: Annotated[AddViaPosition, Field(description="Via position")],
    net: Annotated[str, Field(description="Net name")],
    viaType: Annotated[Optional[str], Field(description="Via type (through, blind, buried)")] = None,
) -> dict[str, Any]:
    """Add a via to the PCB"""
    return dispatch_command("add_via", {"position": position, "net": net, "viaType": viaType})


def copy_routing_pattern(
    sourceRefs: Annotated[List[str], Field(description="References of the source components (e.g. ['U1', 'R1', 'C1'])")],
    targetRefs: Annotated[List[str], Field(description="References of the target components in same order as sourceRefs (e.g. ['U2', 'R2', 'C2'])")],
    includeVias: Annotated[Optional[bool], Field(description="Also copy vias (default: true)")] = None,
    traceWidth: Annotated[Optional[float], Field(description="Override trace width in mm (default: keep original width)")] = None,
) -> dict[str, Any]:
    """Copy routing pattern (traces and vias) from a group of source components to a matching group of target components. The offset is calculated automatically from the position difference between the first source and first target component. Useful for replicating routing between identical circuit blocks."""
    return dispatch_command("copy_routing_pattern", {"sourceRefs": sourceRefs, "targetRefs": targetRefs, "includeVias": includeVias, "traceWidth": traceWidth})


def create_netclass(
    name: Annotated[str, Field(description="Net class name")],
    traceWidth: Annotated[Optional[float], Field(description="Default trace width in mm")] = None,
    clearance: Annotated[Optional[float], Field(description="Clearance in mm")] = None,
    viaDiameter: Annotated[Optional[float], Field(description="Via diameter in mm")] = None,
    viaDrill: Annotated[Optional[float], Field(description="Via drill size in mm")] = None,
) -> dict[str, Any]:
    """Create a new net class with custom design rules."""
    return dispatch_command("create_netclass", {"name": name, "traceWidth": traceWidth, "clearance": clearance, "viaDiameter": viaDiameter, "viaDrill": viaDrill})


def delete_trace(
    traceUuid: Annotated[Optional[str], Field(description="UUID of a specific trace to delete")] = None,
    position: Annotated[Optional[DeleteTracePosition], Field(description="Delete trace nearest to this position")] = None,
    net: Annotated[Optional[str], Field(description="Delete all traces on this net (bulk delete)")] = None,
    layer: Annotated[Optional[str], Field(description="Filter by layer when using net-based deletion")] = None,
    includeVias: Annotated[Optional[bool], Field(description="Include vias in net-based deletion")] = None,
) -> dict[str, Any]:
    """Delete traces from the PCB. Can delete by UUID, position, or bulk-delete all traces on a net."""
    return dispatch_command("delete_trace", {"traceUuid": traceUuid, "position": position, "net": net, "layer": layer, "includeVias": includeVias})


def get_nets_list(
    includeStats: Annotated[Optional[bool], Field(description="Include statistics (track count, total length, etc.)")] = None,
    unit: Annotated[Optional[Literal["mm", "mil", "inch"]], Field(description="Unit for length measurements")] = None,
) -> dict[str, Any]:
    """Get a list of all nets in the PCB with optional statistics."""
    return dispatch_command("get_nets_list", {"includeStats": includeStats, "unit": unit})


def modify_trace(
    traceUuid: Annotated[str, Field(description="UUID of the trace to modify")],
    width: Annotated[Optional[float], Field(description="New trace width in mm")] = None,
    layer: Annotated[Optional[str], Field(description="New layer name")] = None,
    net: Annotated[Optional[str], Field(description="New net name")] = None,
) -> dict[str, Any]:
    """Modify an existing trace (change width, layer, or net)."""
    return dispatch_command("modify_trace", {"traceUuid": traceUuid, "width": width, "layer": layer, "net": net})


def query_traces(
    net: Annotated[Optional[str], Field(description="Filter by net name")] = None,
    layer: Annotated[Optional[str], Field(description="Filter by layer name")] = None,
    boundingBox: Annotated[Optional[QueryTracesBoundingbox], Field(description="Filter by bounding box region")] = None,
    unit: Annotated[Optional[Literal["mm", "inch", "mil"]], Field(description="Unit for coordinates")] = None,
) -> dict[str, Any]:
    """Query traces on the board with optional filters by net, layer, or bounding box."""
    return dispatch_command("query_traces", {"net": net, "layer": layer, "boundingBox": boundingBox, "unit": unit})


def query_zones(
    net: Annotated[Optional[str], Field(description="Filter by net name")] = None,
    layer: Annotated[Optional[str], Field(description="Filter by layer name (matches zones that include this layer)")] = None,
    boundingBox: Annotated[Optional[QueryZonesBoundingbox], Field(description="Filter to zones whose bounding box overlaps this region")] = None,
) -> dict[str, Any]:
    """Query copper zones (filled pours) on the board with optional filters by net, layer, or bounding box. Returns zone net, layers, priority, fill state, and bounding box. Useful for auditing power planes and GND pours that query_traces does not include."""
    return dispatch_command("query_zones", {"net": net, "layer": layer, "boundingBox": boundingBox})


def refill_zones() -> dict[str, Any]:
    """Refill all copper zones on the board. WARNING: SWIG path has known segfault risk (see KNOWN_ISSUES.md). Prefer using IPC backend (KiCAD open) or triggering zone fill via KiCAD UI instead."""
    return dispatch_command("refill_zones", {})


def route_arc_trace(
    start: Annotated[RouteArcTraceStart, Field(description="Arc start position")],
    mid: Annotated[RouteArcTraceMid, Field(description="A point on arc midpoint")],
    end: Annotated[RouteArcTraceEnd, Field(description="Arc end position")],
    layer: Annotated[str, Field(description="PCB layer")],
    width: Annotated[float, Field(description="Trace width in mm")],
    net: Annotated[Optional[str], Field(description="Net name")] = None,
) -> dict[str, Any]:
    """Route a copper arc trace defined by start/mid/end points. Uses true PCB arc primitives when available."""
    return dispatch_command("route_arc_trace", {"start": start, "mid": mid, "end": end, "layer": layer, "width": width, "net": net})


def route_differential_pair(
    positivePad: Annotated[RouteDifferentialPairPositivepad, Field(description="Positive pad (component and pad number)")],
    negativePad: Annotated[RouteDifferentialPairNegativepad, Field(description="Negative pad (component and pad number)")],
    layer: Annotated[str, Field(description="PCB layer")],
    width: Annotated[float, Field(description="Trace width in mm")],
    gap: Annotated[float, Field(description="Gap between traces in mm")],
    positiveNet: Annotated[str, Field(description="Positive net name")],
    negativeNet: Annotated[str, Field(description="Negative net name")],
) -> dict[str, Any]:
    """Route a differential pair between two sets of points."""
    return dispatch_command("route_differential_pair", {"positivePad": positivePad, "negativePad": negativePad, "layer": layer, "width": width, "gap": gap, "positiveNet": positiveNet, "negativeNet": negativeNet})


def route_pad_to_pad(
    fromRef: Annotated[str, Field(description="Reference of the source component (e.g. 'U2')")],
    fromPad: Annotated[Union[str, float], Field(description="Pad number on the source component (e.g. '6' or 6)")],
    toRef: Annotated[str, Field(description="Reference of the target component (e.g. 'U1')")],
    toPad: Annotated[Union[str, float], Field(description="Pad number on the target component (e.g. '15' or 15)")],
    layer: Annotated[Optional[str], Field(description="PCB layer (default: F.Cu)")] = None,
    width: Annotated[Optional[float], Field(description="Trace width in mm (default: board default)")] = None,
    net: Annotated[Optional[str], Field(description="Net name override (default: auto-detected from pad)")] = None,
) -> dict[str, Any]:
    """PREFERRED tool for pad-to-pad routing. Looks up pad positions automatically, detects the net from the pad, and — critically — if the two pads are on different copper layers (e.g. J1 on F.Cu and J2 on B.Cu) automatically inserts a via at the midpoint so the connection is complete. Always use this instead of route_trace when routing between named component pads."""
    return dispatch_command("route_pad_to_pad", {"fromRef": fromRef, "fromPad": fromPad, "toRef": toRef, "toPad": toPad, "layer": layer, "width": width, "net": net})


def route_trace(
    start: Annotated[RouteTraceStart, Field(description="Start position")],
    end: Annotated[RouteTraceEnd, Field(description="End position")],
    layer: Annotated[str, Field(description="PCB layer")],
    width: Annotated[float, Field(description="Trace width in mm")],
    net: Annotated[str, Field(description="Net name")],
) -> dict[str, Any]:
    """Route a trace segment between two XY points on a fixed layer. WARNING: Does NOT handle layer changes — if start and end are on different copper layers, use route_pad_to_pad instead, which automatically inserts a via."""
    return dispatch_command("route_trace", {"start": start, "end": end, "layer": layer, "width": width, "net": net})


_TOOLS = [
    add_copper_pour,
    add_gnd_stitching_vias,
    add_net,
    add_via,
    copy_routing_pattern,
    create_netclass,
    delete_trace,
    get_nets_list,
    modify_trace,
    query_traces,
    query_zones,
    refill_zones,
    route_arc_trace,
    route_differential_pair,
    route_pad_to_pad,
    route_trace,
]


def register(mcp: Any) -> None:
    for fn in _TOOLS:
        mcp.tool()(fn)
