"""schematic-hierarchy toolset — GENERATED by scripts/gen_toolsets.py, do not hand-edit.

Source of truth: tests/fixtures/tools_baseline.json (module "schematic-hierarchy").
"""

from __future__ import annotations

from typing import Annotated, Any, Dict, List, Literal, Optional, Union

from pydantic import BaseModel, Field

from kicad_mcp.toolsets._common import dispatch_command

class AddHierarchicalSheetPosition(BaseModel):
    """Top-left of the sheet box in mm (default 50,50)"""

    x: float
    y: float


class AddHierarchicalSheetSize(BaseModel):
    """Sheet box size in mm (default 80x50)"""

    width: float
    height: float


class CreateHierarchicalSubsheetPosition(BaseModel):
    x: float
    y: float


class CreateHierarchicalSubsheetSize(BaseModel):
    width: float
    height: float

def add_hierarchical_sheet(
    schematicPath: Annotated[str, Field(description="Path to the parent .kicad_sch")],
    subsheetPath: Annotated[str, Field(description="Path to the existing sub-sheet .kicad_sch to reference")],
    sheetName: Annotated[str, Field(description="Display name for the sheet")] = 'Sheet',
    position: Annotated[Optional[AddHierarchicalSheetPosition], Field(description="Top-left of the sheet box in mm (default 50,50)")] = None,
    size: Annotated[Optional[AddHierarchicalSheetSize], Field(description="Sheet box size in mm (default 80x50)")] = None,
) -> dict[str, Any]:
    """Insert a hierarchical-sheet reference block into a parent schematic, pointing at an existing sub-sheet file. Adds the sheet box, name/file fields, a sheet_instances path entry on the next page number, and fixes sub-sheet component instance paths so ERC resolves references."""
    return dispatch_command("add_hierarchical_sheet", {"schematicPath": schematicPath, "subsheetPath": subsheetPath, "sheetName": sheetName, "position": position, "size": size})


def create_hierarchical_subsheet(
    parentSchematicPath: Annotated[str, Field(description="Path to the parent .kicad_sch")],
    subsheetPath: Annotated[str, Field(description="Path for the new sub-sheet .kicad_sch to create")],
    sheetName: Annotated[str, Field(description="Display name for the sheet")] = 'Sheet',
    position: Optional[CreateHierarchicalSubsheetPosition] = None,
    size: Optional[CreateHierarchicalSubsheetSize] = None,
    metadata: Annotated[Optional[Dict[str, Any]], Field(description="Optional metadata for the new sub-sheet (title, etc.)")] = None,
) -> dict[str, Any]:
    """Create a new sub-sheet .kicad_sch file and link it into a parent schematic in a single call (create_schematic + add_hierarchical_sheet). The fastest way to grow a hierarchical design."""
    return dispatch_command("create_hierarchical_subsheet", {"parentSchematicPath": parentSchematicPath, "subsheetPath": subsheetPath, "sheetName": sheetName, "position": position, "size": size, "metadata": metadata})


_TOOLS = [
    add_hierarchical_sheet,
    create_hierarchical_subsheet,
]


def register(mcp: Any) -> None:
    for fn in _TOOLS:
        mcp.tool()(fn)
