"""schematic toolset — GENERATED by scripts/gen_toolsets.py, do not hand-edit.

Source of truth: tests/fixtures/tools_baseline.json (module "schematic").
"""

from __future__ import annotations

from typing import Annotated, Any, Dict, List, Literal, Optional, Union

from pydantic import BaseModel, Field

from kicad_mcp.toolsets._common import dispatch_command

class AddSchematicComponentPosition(BaseModel):
    """Position on schematic"""

    x: float
    y: float


class DeleteSchematicNetLabelPosition(BaseModel):
    """Position to disambiguate if multiple labels with same name"""

    x: float
    y: float


class DeleteSchematicWireStart(BaseModel):
    """Wire start position"""

    x: float
    y: float


class DeleteSchematicWireEnd(BaseModel):
    """Wire end position"""

    x: float
    y: float


class ListSchematicComponentsFilter(BaseModel):
    """Optional filters"""

    libId: Annotated[Optional[str], Field(description="Filter by library ID (e.g., 'Device:R')")] = None
    referencePrefix: Annotated[Optional[str], Field(description="Filter by reference prefix (e.g., 'R', 'C', 'U')")] = None


class MoveSchematicComponentPosition(BaseModel):
    """New position in schematic mm coordinates"""

    x: float
    y: float


class MoveSchematicNetLabelNewposition(BaseModel):
    """Target position in mm"""

    x: float
    y: float


class MoveSchematicNetLabelCurrentposition(BaseModel):
    """Current position to disambiguate when multiple labels share the same name"""

    x: float
    y: float

def add_no_connect(
    schematicPath: Annotated[str, Field(description="Path to the schematic file")],
    position: Annotated[Optional[List[float]], Field(description="Position [x, y] in mm. Required when componentRef/pinNumber are not given.", min_length=2, max_length=2)] = None,
    componentRef: Annotated[Optional[str], Field(description="Component reference to snap to (e.g. U1, R1). Use with pinNumber.")] = None,
    pinNumber: Annotated[Optional[Union[str, float]], Field(description="Pin number or name on componentRef (e.g. '1', 'GND'). Use with componentRef.")] = None,
) -> dict[str, Any]:
    """Add a no-connect flag (X marker) to a pin that is intentionally left unconnected. This suppresses ERC 'Pin not connected' errors for unused pins. PREFERRED: supply componentRef + pinNumber to snap to the exact pin endpoint. Alternatively supply position [x, y] in mm matching the pin endpoint exactly."""
    return dispatch_command("add_no_connect", {"schematicPath": schematicPath, "position": position, "componentRef": componentRef, "pinNumber": pinNumber})


def add_schematic_component(
    schematicPath: Annotated[str, Field(description="Path to the schematic file")],
    symbol: Annotated[str, Field(description="Symbol library:name reference (e.g., Device:R, EDA-MCP:ESP32-C3)")],
    reference: Annotated[str, Field(description="Component reference (e.g., R1, U1)")],
    value: Annotated[Optional[str], Field(description="Component value")] = None,
    footprint: Annotated[Optional[str], Field(description="KiCAD footprint (e.g. Resistor_SMD:R_0603_1608Metric)")] = None,
    position: Annotated[Optional[AddSchematicComponentPosition], Field(description="Position on schematic")] = None,
    unit: Annotated[Optional[int], Field(description="Unit number for multi-unit symbols (1=A, 2=B, 3=C, \u2026). Defaults to 1.", ge=1)] = None,
    angle: Annotated[Optional[float], Field(description="Rotation angle in degrees (KiCad CCW). 0=vertical resistor, 90=horizontal. Defaults to 0.")] = None,
    mirrorY: Annotated[Optional[bool], Field(description="Mirror the symbol horizontally (flip left-right). Useful for transistors facing opposite direction.")] = None,
) -> dict[str, Any]:
    """Add a component to the schematic. Symbol format is 'Library:SymbolName' (e.g., 'Device:R', 'EDA-MCP:ESP32-C3')"""
    return dispatch_command("add_schematic_component", {"schematicPath": schematicPath, "symbol": symbol, "reference": reference, "value": value, "footprint": footprint, "position": position, "unit": unit, "angle": angle, "mirrorY": mirrorY})


def add_schematic_hierarchical_label(
    schematicPath: Annotated[str, Field(description="Path to the sub-sheet .kicad_sch file")],
    text: Annotated[str, Field(description="Label text (e.g. 'SD_CLK') \u2014 must match the sheet pin name")],
    position: Annotated[List[float], Field(description="Position [x, y] in mm", min_length=2, max_length=2)],
    shape: Annotated[Literal["input", "output", "bidirectional"], Field(description="Signal direction from the sub-sheet's perspective")],
    orientation: Annotated[Optional[float], Field(description="Rotation in degrees: 0=label points right, 180=label points left (default: 0)")] = None,
) -> dict[str, Any]:
    """Add a hierarchical label (sheet interface port) to a sub-sheet schematic. Hierarchical labels are the connection points that link a sub-sheet to its parent via sheet pins. The label text must exactly match the corresponding sheet pin name."""
    return dispatch_command("add_schematic_hierarchical_label", {"schematicPath": schematicPath, "text": text, "position": position, "shape": shape, "orientation": orientation})


def add_schematic_net_label(
    schematicPath: Annotated[str, Field(description="Path to the schematic file")],
    netName: Annotated[str, Field(description="Name of the net (e.g., VCC, GND, SIGNAL_1)")],
    position: Annotated[Optional[List[float]], Field(description="Position [x, y] for the label. Required when componentRef/pinNumber are not given.", min_length=2, max_length=2)] = None,
    componentRef: Annotated[Optional[str], Field(description="Component reference to snap label to (e.g. U1, R1). Use with pinNumber.")] = None,
    pinNumber: Annotated[Optional[Union[str, float]], Field(description="Pin number or name on componentRef to snap label to (e.g. '1', 'GND'). Use with componentRef.")] = None,
    labelType: Annotated[Optional[Literal["label", "global_label", "hierarchical_label"]], Field(description="Label type (default: label)")] = None,
    orientation: Annotated[Optional[float], Field(description="Rotation angle 0/90/180/270 (default: 0)")] = None,
) -> dict[str, Any]:
    """Add a net label to the schematic. PREFERRED: supply componentRef + pinNumber to snap the label to the exact pin endpoint — this guarantees an electrical connection. Alternatively supply position [x, y], but the coordinates must match the pin endpoint exactly (even a 0.01 mm offset breaks the connection). The response includes actual_position (coordinates actually used) and snapped_to_pin (present when a pin reference was resolved)."""
    return dispatch_command("add_schematic_net_label", {"schematicPath": schematicPath, "netName": netName, "position": position, "componentRef": componentRef, "pinNumber": pinNumber, "labelType": labelType, "orientation": orientation})


def add_schematic_text(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch file")],
    text: Annotated[str, Field(description="Text content to display")],
    position: Annotated[List[float], Field(description="Position [x, y] in schematic mm coordinates", min_length=2, max_length=2)],
    angle: Annotated[Optional[float], Field(description="Rotation angle in degrees (default: 0)")] = None,
    fontSize: Annotated[Optional[float], Field(description="Font size in mm (default: 1.27)")] = None,
    bold: Annotated[Optional[bool], Field(description="Bold text (default: false)")] = None,
    italic: Annotated[Optional[bool], Field(description="Italic text (default: false)")] = None,
    justify: Annotated[Optional[Literal["left", "center", "right"]], Field(description="Horizontal text justification (default: left)")] = None,
) -> dict[str, Any]:
    """Add a free-form text annotation to the schematic. Use this to add notes, labels, section headings, or documentation strings directly on the schematic canvas. Unlike net labels, text annotations have no electrical significance."""
    return dispatch_command("add_schematic_text", {"schematicPath": schematicPath, "text": text, "position": position, "angle": angle, "fontSize": fontSize, "bold": bold, "italic": italic, "justify": justify})


def add_schematic_wire(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch file")],
    waypoints: Annotated[List[List[float]], Field(description="Ordered list of [x, y] coordinates. Minimum 2 points.", min_length=2)],
    snapToPins: Annotated[Optional[bool], Field(description="Snap the first and last waypoints to the nearest pin (default: true)")] = None,
    snapTolerance: Annotated[Optional[float], Field(description="Maximum snap distance in mm (default: 1.0)")] = None,
) -> dict[str, Any]:
    """Draws a wire on the schematic between two or more coordinate points. Always call get_schematic_pin_locations first to get the approximate pin coordinates, then pass them as the first and last waypoints. snapToPins (on by default) will correct any float imprecision by snapping endpoints to the exact nearest pin coordinate. To route around components, add intermediate waypoints between the start and end: e.g. [[x1,y1], [xMid,y1], [xMid,y2], [x2,y2]] routes horizontally then vertically. Intermediate waypoints are never snapped."""
    return dispatch_command("add_schematic_wire", {"schematicPath": schematicPath, "waypoints": waypoints, "snapToPins": snapToPins, "snapTolerance": snapTolerance})


def add_sheet_pin(
    schematicPath: Annotated[str, Field(description="Path to the PARENT .kicad_sch file")],
    sheetName: Annotated[str, Field(description="Sheet name as it appears in the Sheetname property (e.g. 'Storage')")],
    pinName: Annotated[str, Field(description="Pin name \u2014 must match a hierarchical_label in the sub-sheet")],
    pinType: Annotated[Literal["input", "output", "bidirectional"], Field(description="Signal direction (should match the sub-sheet hierarchical label shape)")],
    position: Annotated[List[float], Field(description="Pin position [x, y] in mm \u2014 must be on the sheet block boundary", min_length=2, max_length=2)],
    orientation: Annotated[Optional[float], Field(description="Pin orientation: 0=right edge of sheet box, 180=left edge (default: 0)")] = None,
) -> dict[str, Any]:
    """Add a pin to a sheet symbol block on the parent schematic. Sheet pins are the parent-side connection points that correspond to hierarchical labels in the sub-sheet. The pinName must exactly match a hierarchical_label in the sub-sheet."""
    return dispatch_command("add_sheet_pin", {"schematicPath": schematicPath, "sheetName": sheetName, "pinName": pinName, "pinType": pinType, "position": position, "orientation": orientation})


def annotate_schematic(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch file")],
) -> dict[str, Any]:
    """Assign reference designators to unannotated components (R? → R1, R2, ...). Must be called before tools that require known references."""
    return dispatch_command("annotate_schematic", {"schematicPath": schematicPath})


def connect_passthrough(
    schematicPath: Annotated[str, Field(description="Path to the schematic file")],
    sourceRef: Annotated[str, Field(description="Source connector reference (e.g. J1)")],
    targetRef: Annotated[str, Field(description="Target connector reference (e.g. J2)")],
    netPrefix: Annotated[Optional[str], Field(description="Net name prefix, e.g. 'CSI' \u2192 CSI_1, CSI_2 (default: PIN)")] = None,
    pinOffset: Annotated[Optional[float], Field(description="Add to pin number when building net name (default: 0)")] = None,
) -> dict[str, Any]:
    """Connects all pins of a source connector (e.g. J1) to matching pins of a target connector (e.g. J2) via shared net labels — pin N gets net '{netPrefix}_{N}'. Use this for FFC/ribbon cable passthrough adapters instead of calling connect_to_net for every pin."""
    return dispatch_command("connect_passthrough", {"schematicPath": schematicPath, "sourceRef": sourceRef, "targetRef": targetRef, "netPrefix": netPrefix, "pinOffset": pinOffset})


def connect_to_net(
    schematicPath: Annotated[str, Field(description="Path to the schematic file")],
    componentRef: Annotated[str, Field(description="Component reference (e.g., U1, R1)")],
    pinName: Annotated[str, Field(description="Pin name/number to connect")],
    netName: Annotated[str, Field(description="Name of the net to connect to")],
) -> dict[str, Any]:
    """Connect a component pin to a named net by adding a wire stub and net label at the exact pin endpoint. The response includes pin_location (exact pin coords), label_location (where the label was placed), and wire_stub (the wire segment added) so you can confirm the placement."""
    return dispatch_command("connect_to_net", {"schematicPath": schematicPath, "componentRef": componentRef, "pinName": pinName, "netName": netName})


def create_schematic(
    name: Annotated[str, Field(description="Schematic name")],
    path: Annotated[Optional[str], Field(description="Optional path")] = None,
) -> dict[str, Any]:
    """Create a new schematic"""
    return dispatch_command("create_schematic", {"name": name, "path": path})


def delete_schematic_component(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch file")],
    reference: Annotated[str, Field(description="Reference designator of the component to remove (e.g. R1, U3)")],
) -> dict[str, Any]:
    """Remove a placed symbol from a KiCAD schematic (.kicad_sch).

This removes the symbol instance (the placed component) from the schematic.
It does NOT remove the symbol definition from lib_symbols.

Note: This tool operates on schematic files (.kicad_sch).
To remove a footprint from a PCB, use delete_component instead."""
    return dispatch_command("delete_schematic_component", {"schematicPath": schematicPath, "reference": reference})


def delete_schematic_net_label(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch file")],
    netName: Annotated[str, Field(description="Name of the net label to remove")],
    position: Annotated[Optional[DeleteSchematicNetLabelPosition], Field(description="Position to disambiguate if multiple labels with same name")] = None,
) -> dict[str, Any]:
    """Remove a net label from the schematic."""
    return dispatch_command("delete_schematic_net_label", {"schematicPath": schematicPath, "netName": netName, "position": position})


def delete_schematic_wire(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch file")],
    start: Annotated[DeleteSchematicWireStart, Field(description="Wire start position")],
    end: Annotated[DeleteSchematicWireEnd, Field(description="Wire end position")],
) -> dict[str, Any]:
    """Remove a wire from the schematic by start and end coordinates."""
    return dispatch_command("delete_schematic_wire", {"schematicPath": schematicPath, "start": start, "end": end})


def edit_schematic_component(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch file")],
    reference: Annotated[str, Field(description="Current reference designator of the component (e.g. R1, U3)")],
    footprint: Annotated[Optional[str], Field(description="New KiCAD footprint string (e.g. Resistor_SMD:R_0603_1608Metric)")] = None,
    value: Annotated[Optional[str], Field(description="New value string (e.g. 10k, 100nF)")] = None,
    newReference: Annotated[Optional[str], Field(description="Rename the reference designator (e.g. R1 \u2192 R10)")] = None,
    fieldPositions: Annotated[Optional[Dict[str, Any]], Field(description="Reposition field labels: map of field name to {x, y, angle, justify?} (e.g. {\"Reference\": {\"x\": 12.5, \"y\": 17.0, \"justify\": \"left\"}})")] = None,
    properties: Annotated[Optional[Dict[str, Any]], Field(description="Add or update component properties. Map of property name to either a string value (sensible defaults) or a full spec object {value, x?, y?, angle?, hide?, fontSize?}. Use this to attach BOM and sourcing metadata such as MPN, Manufacturer, Distributor, DigiKey, LCSC, JLCPCB_PN, Voltage, Tolerance, Dielectric, Power, etc. Built-in fields (Reference, Value, Footprint, Datasheet) can also be set this way but the dedicated parameters above are clearer. Example: {\"MPN\": \"RC0603FR-0710KL\", \"Manufacturer\": \"Yageo\", \"Tolerance\": \"1%\"}")] = None,
    removeProperties: Annotated[Optional[List[str]], Field(description="List of custom property names to delete from this component. The built-in fields Reference, Value, Footprint, and Datasheet cannot be removed (clear them by setting value to \"\" instead). Example: [\"OldMPN\", \"Distributor_PN\"]")] = None,
) -> dict[str, Any]:
    """Update properties of a placed symbol in a KiCAD schematic (.kicad_sch) in-place.

Use this tool to:
  • assign or update the footprint, value, or reference designator,
  • reposition field labels (Reference / Value text),
  • add, update, or remove ARBITRARY CUSTOM PROPERTIES used by BOM and sourcing
    workflows: MPN, Manufacturer, Manufacturer_PN, Distributor, DigiKey, DigiKey_PN,
    Mouser_PN, LCSC, JLCPCB_PN, Voltage, Tolerance, Power, Dielectric, etc.

Custom properties are first-class — they survive ERC, are exported by export_bom,
and are picked up by the JLCPCB / Digi-Key BOM tooling. Newly-added properties
default to hidden so they do not clutter the schematic canvas.

Multiple updates can be batched in a single call: pass any combination of
`footprint`, `value`, `newReference`, `fieldPositions`, `properties`,
and `removeProperties` together.

This is more efficient than delete + re-add because it preserves the component's
position and UUID. Operates on .kicad_sch files only — to modify a PCB footprint
use edit_component instead."""
    return dispatch_command("edit_schematic_component", {"schematicPath": schematicPath, "reference": reference, "footprint": footprint, "value": value, "newReference": newReference, "fieldPositions": fieldPositions, "properties": properties, "removeProperties": removeProperties})


def export_schematic_pdf(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch file")],
    outputPath: Annotated[str, Field(description="Output PDF file path")],
    blackAndWhite: Annotated[Optional[bool], Field(description="Export in black and white")] = None,
) -> dict[str, Any]:
    """Export schematic to PDF format using kicad-cli."""
    return dispatch_command("export_schematic_pdf", {"schematicPath": schematicPath, "outputPath": outputPath, "blackAndWhite": blackAndWhite})


def export_schematic_svg(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch file")],
    outputPath: Annotated[str, Field(description="Output SVG file path")],
    blackAndWhite: Annotated[Optional[bool], Field(description="Export in black and white")] = None,
) -> dict[str, Any]:
    """Export schematic to SVG format using kicad-cli."""
    return dispatch_command("export_schematic_svg", {"schematicPath": schematicPath, "outputPath": outputPath, "blackAndWhite": blackAndWhite})


def find_orphaned_wires(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch schematic file")],
) -> dict[str, Any]:
    """Find wire segments with at least one dangling endpoint — not connected to a component pin, net label, or another wire. Orphaned wires cause ERC 'wire end unconnected' errors. Does not require the KiCad UI to be running."""
    return dispatch_command("find_orphaned_wires", {"schematicPath": schematicPath})


def find_overlapping_elements(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch schematic file")],
    tolerance: Annotated[Optional[float], Field(description="Distance threshold in mm for label proximity and wire collinearity checks. Symbol overlap uses bounding-box intersection. (default: 0.5)")] = None,
) -> dict[str, Any]:
    """Detect spatially overlapping symbols, wires, and labels in the schematic. Finds duplicate power symbols at the same position, collinear overlapping wires, and labels stacked on top of each other."""
    return dispatch_command("find_overlapping_elements", {"schematicPath": schematicPath, "tolerance": tolerance})


def find_wires_crossing_symbols(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch schematic file")],
) -> dict[str, Any]:
    """Find all wires that cross over component symbol bodies. Wires passing over symbols are unacceptable in schematics — they indicate routing mistakes where a wire was drawn across a component instead of around it."""
    return dispatch_command("find_wires_crossing_symbols", {"schematicPath": schematicPath})


def generate_netlist(
    schematicPath: Annotated[str, Field(description="Absolute path to the .kicad_sch schematic file")],
) -> dict[str, Any]:
    """Return a structured JSON netlist from the schematic — component list (reference, value, footprint) and net list (net name with all connected component/pin pairs). Use this to inspect or verify connectivity within the conversation. Does not write any file. To export a netlist file in Spice, KiCad XML, Cadstar, or OrcadPCB2 format, use export_netlist instead."""
    return dispatch_command("generate_netlist", {"schematicPath": schematicPath})


def get_elements_in_region(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch schematic file")],
    x1: Annotated[float, Field(description="Left X coordinate of the region in mm")],
    y1: Annotated[float, Field(description="Top Y coordinate of the region in mm")],
    x2: Annotated[float, Field(description="Right X coordinate of the region in mm")],
    y2: Annotated[float, Field(description="Bottom Y coordinate of the region in mm")],
) -> dict[str, Any]:
    """List all symbols, wires, and labels within a rectangular region of the schematic. Useful for understanding what is in a specific area before modifying it."""
    return dispatch_command("get_elements_in_region", {"schematicPath": schematicPath, "x1": x1, "y1": y1, "x2": x2, "y2": y2})


def get_net_at_point(
    schematicPath: Annotated[str, Field(description="Path to the schematic file (.kicad_sch)")],
    x: Annotated[float, Field(description="X coordinate in mm")],
    y: Annotated[float, Field(description="Y coordinate in mm")],
) -> dict[str, Any]:
    """Returns the net name at a given (x, y) coordinate in a schematic, or null if no net label or wire endpoint is present at that position. Faster than get_pin_net when you only need the net name at a known coordinate and don't need pin traversal."""
    return dispatch_command("get_net_at_point", {"schematicPath": schematicPath, "x": x, "y": y})


def get_net_connections(
    schematicPath: Annotated[str, Field(description="Path to the schematic file")],
    netName: Annotated[str, Field(description="Name of the net to query")],
) -> dict[str, Any]:
    """Get all connections for a named net"""
    return dispatch_command("get_net_connections", {"schematicPath": schematicPath, "netName": netName})


def get_schematic_component(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch file")],
    reference: Annotated[str, Field(description="Component reference designator (e.g. R1, U1)")],
) -> dict[str, Any]:
    """Get full component info from a schematic: position, every field's value, and each field's label position (at x/y/angle). Returns ALL properties — both built-in fields (Reference, Value, Footprint, Datasheet) and any custom BOM/sourcing properties present on the symbol (MPN, Manufacturer, DigiKey_PN, LCSC, Voltage, Tolerance, Dielectric, etc.). Use this before edit_schematic_component / set_schematic_component_property to inspect what is currently set, or to plan a label repositioning."""
    return dispatch_command("get_schematic_component", {"schematicPath": schematicPath, "reference": reference})


def get_schematic_pin_locations(
    schematicPath: Annotated[str, Field(description="Path to the schematic file")],
    reference: Annotated[str, Field(description="Component reference designator (e.g. U1, R1, J2)")],
) -> dict[str, Any]:
    """Returns the exact x/y coordinates of every pin on a schematic component. Use this before add_schematic_net_label to place labels correctly on pin endpoints."""
    return dispatch_command("get_schematic_pin_locations", {"schematicPath": schematicPath, "reference": reference})


def get_schematic_view(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch file")],
    format: Annotated[Optional[Literal["png", "svg"]], Field(description="Output format (default: png)")] = None,
    width: Annotated[Optional[float], Field(description="Image width in pixels (default: 1200)")] = None,
    height: Annotated[Optional[float], Field(description="Image height in pixels (default: 900)")] = None,
) -> dict[str, Any]:
    """Return a rasterized image of the schematic (PNG by default, or SVG). Uses kicad-cli to export SVG, then converts to PNG via cairosvg. Use this for visual feedback after placing or wiring components."""
    return dispatch_command("get_schematic_view", {"schematicPath": schematicPath, "format": format, "width": width, "height": height})


def get_schematic_view_region(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch schematic file")],
    x1: Annotated[float, Field(description="Left X coordinate of the region in mm")],
    y1: Annotated[float, Field(description="Top Y coordinate of the region in mm")],
    x2: Annotated[float, Field(description="Right X coordinate of the region in mm")],
    y2: Annotated[float, Field(description="Bottom Y coordinate of the region in mm")],
    format: Annotated[Optional[Literal["png", "svg"]], Field(description="Output image format (default: png)")] = None,
    width: Annotated[Optional[float], Field(description="Output image width in pixels (default: 800)")] = None,
    height: Annotated[Optional[float], Field(description="Output image height in pixels (default: 600)")] = None,
) -> dict[str, Any]:
    """Export a cropped region of the schematic as an image (PNG or SVG). Specify bounding box coordinates in schematic mm. Useful for zooming into a specific area to inspect wiring or layout."""
    return dispatch_command("get_schematic_view_region", {"schematicPath": schematicPath, "x1": x1, "y1": y1, "x2": x2, "y2": y2, "format": format, "width": width, "height": height})


def get_wire_connections(
    schematicPath: Annotated[str, Field(description="Path to the schematic file")],
    reference: Annotated[Optional[str], Field(description="Component reference (e.g. U1, R1). Pair with pin.")] = None,
    pin: Annotated[Optional[str], Field(description="Pin number or name (e.g. '3', 'SDA'). Pair with reference.")] = None,
    x: Annotated[Optional[float], Field(description="X coordinate of a wire endpoint in mm. Pair with y.")] = None,
    y: Annotated[Optional[float], Field(description="Y coordinate of a wire endpoint in mm. Pair with x.")] = None,
) -> dict[str, Any]:
    """Returns the net name and all wires and component pins connected at a given point. Accepts either a component reference + pin number (e.g. reference='U1', pin='3') or a schematic coordinate (x, y in mm). Returns net=null for unnamed (unlabelled) nets. The query point must be at a wire endpoint or junction — midpoints are not matched. Use get_schematic_pin_locations or list_schematic_wires to obtain exact endpoint coordinates."""
    return dispatch_command("get_wire_connections", {"schematicPath": schematicPath, "reference": reference, "pin": pin, "x": x, "y": y})


def list_floating_labels(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch schematic file")],
) -> dict[str, Any]:
    """Returns all net labels in the schematic that are not connected to any component pin. A label is 'floating' when no component pin falls on the wire-network reachable from the label's position. Floating labels indicate misplaced or off-grid labels that cause ERC errors. Does not require the KiCAD UI to be running."""
    return dispatch_command("list_floating_labels", {"schematicPath": schematicPath})


def list_schematic_components(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch file")],
    filter: Annotated[Optional[ListSchematicComponentsFilter], Field(description="Optional filters")] = None,
) -> dict[str, Any]:
    """List all components in a schematic with their references, values, positions, and pins. Essential for inspecting what's on the schematic before making edits."""
    return dispatch_command("list_schematic_components", {"schematicPath": schematicPath, "filter": filter})


def list_schematic_labels(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch file")],
    netName: Annotated[Optional[str], Field(description="Filter to labels whose name exactly matches this string (case-sensitive). Omit to return all labels.")] = None,
    labelType: Annotated[Optional[Literal["net", "global", "power"]], Field(description="Filter by label type. 'net' = local label, 'global' = global label, 'power' = power symbol. Omit to return all types.")] = None,
) -> dict[str, Any]:
    """List all net labels, global labels, and power flags in the schematic. Optionally filter by label name (netName) and/or label type (labelType)."""
    return dispatch_command("list_schematic_labels", {"schematicPath": schematicPath, "netName": netName, "labelType": labelType})


def list_schematic_nets(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch file")],
) -> dict[str, Any]:
    """List all nets in the schematic with their connections."""
    return dispatch_command("list_schematic_nets", {"schematicPath": schematicPath})


def list_schematic_texts(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch file")],
    text: Annotated[Optional[str], Field(description="Case-insensitive substring filter \u2014 only return texts containing this string")] = None,
) -> dict[str, Any]:
    """List all free-form text annotations (notes, headings, documentation strings) in the schematic. Returns position, angle, font size, bold/italic flags, and justification for each text element. Optionally filter by a substring match on the text content."""
    return dispatch_command("list_schematic_texts", {"schematicPath": schematicPath, "text": text})


def list_schematic_wires(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch file")],
) -> dict[str, Any]:
    """List all wires in the schematic with start/end coordinates."""
    return dispatch_command("list_schematic_wires", {"schematicPath": schematicPath})


def move_schematic_component(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch file")],
    reference: Annotated[str, Field(description="Reference designator (e.g., R1, U1)")],
    position: Annotated[MoveSchematicComponentPosition, Field(description="New position in schematic mm coordinates")],
    preserveWires: Annotated[Optional[bool], Field(description="Stretch connected wire endpoints to follow the move (default true)")] = None,
) -> dict[str, Any]:
    """Move a placed symbol to a new position in the schematic. By default (preserveWires=true) wire endpoints touching the component's pins are stretched to follow the new position."""
    return dispatch_command("move_schematic_component", {"schematicPath": schematicPath, "reference": reference, "position": position, "preserveWires": preserveWires})


def move_schematic_net_label(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch file")],
    netName: Annotated[str, Field(description="Name of the net label to move")],
    newPosition: Annotated[MoveSchematicNetLabelNewposition, Field(description="Target position in mm")],
    currentPosition: Annotated[Optional[MoveSchematicNetLabelCurrentposition], Field(description="Current position to disambiguate when multiple labels share the same name")] = None,
    labelType: Annotated[Optional[Literal["label", "global_label", "hierarchical_label"]], Field(description="Restrict search to a specific label type")] = None,
) -> dict[str, Any]:
    """Move a net label (local, global, or hierarchical) to a new position in the schematic. Use currentPosition to disambiguate when multiple labels share the same name."""
    return dispatch_command("move_schematic_net_label", {"schematicPath": schematicPath, "netName": netName, "newPosition": newPosition, "currentPosition": currentPosition, "labelType": labelType})


def remove_schematic_component_property(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch file")],
    reference: Annotated[str, Field(description="Reference designator of the component (e.g. R1, U3)")],
    name: Annotated[str, Field(description="Custom property name to remove (e.g. 'MPN', 'Distributor_PN', 'OldField')")],
) -> dict[str, Any]:
    """Remove a single custom property from a placed schematic symbol.

Built-in fields (Reference, Value, Footprint, Datasheet) cannot be removed —
KiCad requires them on every symbol. To clear a built-in field, use
edit_schematic_component and set its value to an empty string."""
    return dispatch_command("remove_schematic_component_property", {"schematicPath": schematicPath, "reference": reference, "name": name})


def rotate_schematic_component(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch file")],
    reference: Annotated[str, Field(description="Reference designator (e.g., R1, U1)")],
    angle: Annotated[float, Field(description="Absolute rotation in degrees (0, 90, 180, 270). This is the symbol's final orientation, not a relative increment \u2014 passing 90 sets the symbol to 90\u00b0 regardless of its current angle (unlike KiCad's UI 'R' key).")],
    mirror: Annotated[Optional[Literal["x", "y"]], Field(description="Optional mirror axis")] = None,
) -> dict[str, Any]:
    """Rotate a placed symbol in the schematic."""
    return dispatch_command("rotate_schematic_component", {"schematicPath": schematicPath, "reference": reference, "angle": angle, "mirror": mirror})


def run_erc(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch schematic file")],
) -> dict[str, Any]:
    """Runs the KiCAD Electrical Rules Check (ERC) on a schematic and returns all violations. Use after wiring to verify the schematic before generating a netlist."""
    return dispatch_command("run_erc", {"schematicPath": schematicPath})


def set_schematic_component_property(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch file")],
    reference: Annotated[str, Field(description="Reference designator of the component (e.g. R1, U3)")],
    name: Annotated[str, Field(description="Property name (e.g. 'MPN', 'Manufacturer', 'DigiKey_PN', 'Voltage', 'Dielectric')")],
    value: Annotated[str, Field(description="Property value to write (use empty string to clear)")],
    x: Annotated[Optional[float], Field(description="Label X position in mm (default: component X)")] = None,
    y: Annotated[Optional[float], Field(description="Label Y position in mm (default: component Y)")] = None,
    angle: Annotated[Optional[float], Field(description="Label rotation in degrees (default: 0)")] = None,
    hide: Annotated[Optional[bool], Field(description="Hide the property text on the schematic canvas. Defaults to true for newly-created custom properties.")] = None,
    fontSize: Annotated[Optional[float], Field(description="Font size in mm for the label (default: 1.27)")] = None,
    justify: Annotated[Optional[str], Field(description="Text justification for the property label. KiCad alignment keywords: \"left\", \"right\", \"center\", \"top\", \"bottom\", or combined e.g. \"left top\". Omit to leave unchanged. Pass \"center\" to reset to the KiCad default.")] = None,
) -> dict[str, Any]:
    """Add or update a single custom property on a placed schematic symbol.

This is a focused convenience wrapper around edit_schematic_component for the very
common case of attaching one BOM / sourcing field at a time. The property is
created if it does not already exist on the component.

Typical custom properties:
  • MPN, Manufacturer, Manufacturer_PN — manufacturer part number metadata
  • DigiKey, DigiKey_PN, Mouser_PN, LCSC, JLCPCB_PN — distributor part numbers
  • Voltage, Tolerance, Power, Dielectric, Temperature_Coefficient — passive parameters
  • Description, Notes — free-form documentation
  • Any custom field your BOM exporter expects.

These properties are written into the .kicad_sch file as standard KiCad property
records, are exported by export_bom, and are picked up by the JLCPCB and Digi-Key
sourcing tools. Newly-created properties default to hidden — set hide=false to
display the value on the schematic canvas.

For batch updates of multiple properties at once, use edit_schematic_component
with the `properties` parameter instead."""
    return dispatch_command("set_schematic_component_property", {"schematicPath": schematicPath, "reference": reference, "name": name, "value": value, "x": x, "y": y, "angle": angle, "hide": hide, "fontSize": fontSize, "justify": justify})


def snap_to_grid(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch schematic file")],
    gridSize: Annotated[Optional[float], Field(description="Grid spacing in mm (default: 2.54 \u2014 standard KiCAD schematic grid)")] = None,
    elements: Annotated[Optional[List[Literal["wires", "junctions", "labels", "components"]]], Field(description="Element types to snap (default: [\"wires\", \"junctions\", \"labels\"]). \"components\" is opt-in \u2014 moving a component without re-routing wires creates new mismatches.")] = None,
) -> dict[str, Any]:
    """Snap schematic element coordinates to the nearest grid point. KiCAD uses exact integer matching for connectivity, so off-grid coordinates cause wires that look connected to fail ERC checks. Modifies the .kicad_sch file in place. Does not require the KiCAD UI to be running."""
    return dispatch_command("snap_to_grid", {"schematicPath": schematicPath, "gridSize": gridSize, "elements": elements})


def sync_schematic_to_board(
    schematicPath: Annotated[str, Field(description="Absolute path to the .kicad_sch schematic file")],
    boardPath: Annotated[str, Field(description="Absolute path to the .kicad_pcb board file")],
) -> dict[str, Any]:
    """Import the schematic netlist into the PCB board — equivalent to pressing F8 in KiCAD (Tools → Update PCB from Schematic). MUST be called after the schematic is complete and before placing or routing components on the PCB. Without this step, the board has no footprints and no net assignments — place_component and route_pad_to_pad will produce an empty, unroutable board."""
    return dispatch_command("sync_schematic_to_board", {"schematicPath": schematicPath, "boardPath": boardPath})


_TOOLS = [
    add_no_connect,
    add_schematic_component,
    add_schematic_hierarchical_label,
    add_schematic_net_label,
    add_schematic_text,
    add_schematic_wire,
    add_sheet_pin,
    annotate_schematic,
    connect_passthrough,
    connect_to_net,
    create_schematic,
    delete_schematic_component,
    delete_schematic_net_label,
    delete_schematic_wire,
    edit_schematic_component,
    export_schematic_pdf,
    export_schematic_svg,
    find_orphaned_wires,
    find_overlapping_elements,
    find_wires_crossing_symbols,
    generate_netlist,
    get_elements_in_region,
    get_net_at_point,
    get_net_connections,
    get_schematic_component,
    get_schematic_pin_locations,
    get_schematic_view,
    get_schematic_view_region,
    get_wire_connections,
    list_floating_labels,
    list_schematic_components,
    list_schematic_labels,
    list_schematic_nets,
    list_schematic_texts,
    list_schematic_wires,
    move_schematic_component,
    move_schematic_net_label,
    remove_schematic_component_property,
    rotate_schematic_component,
    run_erc,
    set_schematic_component_property,
    snap_to_grid,
    sync_schematic_to_board,
]


def register(mcp: Any) -> None:
    for fn in _TOOLS:
        mcp.tool()(fn)
