"""schematic-batch toolset — GENERATED by scripts/gen_toolsets.py, do not hand-edit.

Source of truth: tests/fixtures/tools_baseline.json (module "schematic-batch").
"""

from __future__ import annotations

from typing import Annotated, Any, Dict, List, Literal, Optional, Union

from pydantic import BaseModel, Field

from kicad_mcp.toolsets._common import dispatch_command

class AddLibrarySymbolPropertyPosition(BaseModel):
    """Position {x, y} in mm (default: 0, 0)"""

    x: float
    y: float


class BatchAddAndConnectComponentsItemPosition(BaseModel):
    x: float
    y: float


class BatchAddAndConnectComponentsItem(BaseModel):
    symbol: str
    reference: str
    value: Optional[str] = None
    footprint: Optional[str] = None
    position: Optional[BatchAddAndConnectComponentsItemPosition] = None
    rotation: Optional[float] = None
    nets: Annotated[Optional[Dict[str, Any]], Field(description="Map of pin -> netName to label after placement")] = None


class BatchAddComponentsComponentsItemPosition(BaseModel):
    x: float
    y: float


class BatchAddComponentsComponentsItem(BaseModel):
    symbol: Annotated[str, Field(description="'Library:SymbolName' (e.g., Device:R)")]
    reference: Annotated[str, Field(description="Reference designator (e.g., R1)")]
    value: Optional[str] = None
    footprint: Optional[str] = None
    position: Optional[BatchAddComponentsComponentsItemPosition] = None
    rotation: Optional[float] = None
    includePins: Optional[bool] = None


class BatchAddNoConnectsPinsItem(BaseModel):
    componentRef: str
    pinName: str

def add_library_symbol_property(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch file")],
    libraryName: Annotated[str, Field(description="Symbol library nickname (e.g. Device, power)")],
    symbolName: Annotated[str, Field(description="Symbol name (e.g. R, C, GND)")],
    propertyName: Annotated[str, Field(description="Property name (e.g. Manufacturer, MPN)")],
    propertyValue: Annotated[str, Field(description="Property value")],
    position: Annotated[Optional[AddLibrarySymbolPropertyPosition], Field(description="Position {x, y} in mm (default: 0, 0)")] = None,
    hide: Annotated[Optional[bool], Field(description="Hide the property (default false)")] = None,
) -> dict[str, Any]:
    """Add or update a custom property (Manufacturer, MPN, LCSC, etc.) on a symbol definition in the lib_symbols section. This makes the property available to all instances of that symbol in the schematic."""
    return dispatch_command("add_library_symbol_property", {"schematicPath": schematicPath, "libraryName": libraryName, "symbolName": symbolName, "propertyName": propertyName, "propertyValue": propertyValue, "position": position, "hide": hide})


def batch_add_and_connect(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch file")],
    components: Annotated[List[BatchAddAndConnectComponentsItem], Field(description="Components to place and connect")],
    origin_x: Optional[float] = None,
    origin_y: Optional[float] = None,
) -> dict[str, Any]:
    """Place multiple components AND wire their nets in a single call — the fewest-round-trip way to build a subcircuit. Each component is like batch_add_components plus an optional 'nets' map {pin: netName}. Components are placed first, then nets are connected via batch_connect."""
    return dispatch_command("batch_add_and_connect", {"schematicPath": schematicPath, "components": components, "origin_x": origin_x, "origin_y": origin_y})


def batch_add_components(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch file")],
    components: Annotated[List[BatchAddComponentsComponentsItem], Field(description="Components to place")],
    origin_x: Annotated[Optional[float], Field(description="X offset added to every component position (mm)")] = None,
    origin_y: Annotated[Optional[float], Field(description="Y offset added to every component position (mm)")] = None,
    auto_position_fields: Annotated[bool, Field(description="Auto-place Ref/Value fields outside the body (default true)")] = True,
) -> dict[str, Any]:
    """Add multiple components to a schematic in one call (far fewer round-trips than add_schematic_component). Each component: {symbol:'Library:Name', reference, value?, footprint?, position:{x,y}, rotation?, includePins?}. Reference/Value fields are auto-positioned outside the body (disable with auto_position_fields=false). Returns per-component snapped position, field positions, body_bbox, and an overall placement_bbox."""
    return dispatch_command("batch_add_components", {"schematicPath": schematicPath, "components": components, "origin_x": origin_x, "origin_y": origin_y, "auto_position_fields": auto_position_fields})


def batch_add_no_connects(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch file")],
    pins: Annotated[List[BatchAddNoConnectsPinsItem], Field(description="Pins to mark no-connect")],
) -> dict[str, Any]:
    """Add no-connect (X) flags to multiple pins in one call, to mark intentionally unconnected pins and silence ERC. 'pins' is a list of {componentRef, pinName}."""
    return dispatch_command("batch_add_no_connects", {"schematicPath": schematicPath, "pins": pins})


def batch_connect(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch file")],
    connections: Annotated[Dict[str, Any], Field(description="Map of reference -> {pin: netName}")],
    replace: Annotated[bool, Field(description="Delete existing labels at each pin before placing (default false)")] = False,
) -> dict[str, Any]:
    """Place net labels on multiple pins in one call to wire nets quickly. 'connections' is a map {reference: {pin: netName}} where pin is a number or name. If a facing label for the same net is nearby, a wire is drawn instead of a duplicate label. Set replace=true to clear any existing label at a pin first. Warns about power nets missing a PWR_FLAG."""
    return dispatch_command("batch_connect", {"schematicPath": schematicPath, "connections": connections, "replace": replace})


def batch_edit_schematic_components(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch file")],
    components: Annotated[Dict[str, Any], Field(description="Map of reference -> fields to change")],
) -> dict[str, Any]:
    """Edit multiple existing components in one call. 'components' is a map {reference: {value?, footprint?, newReference?, ...}}; each entry is applied via the single-component editor. Returns per-reference updated/errors."""
    return dispatch_command("batch_edit_schematic_components", {"schematicPath": schematicPath, "components": components})


def replace_schematic_component(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch file")],
    reference: Annotated[str, Field(description="Reference of the component to replace (e.g., D1)")],
    newSymbol: Annotated[str, Field(description="New symbol in 'Library:Symbol' form (e.g., Device:D_Zener)")],
    newRotation: Annotated[Optional[float], Field(description="Override rotation in degrees (default: keep existing)")] = None,
) -> dict[str, Any]:
    """Replace a placed component's symbol with a different one (e.g. Device:R -> Device:R_Potentiometer), preserving its position, rotation, and field values (Value/Footprint/custom). Optionally override rotation with newRotation. Returns the new pin positions."""
    return dispatch_command("replace_schematic_component", {"schematicPath": schematicPath, "reference": reference, "newSymbol": newSymbol, "newRotation": newRotation})


def update_symbol_from_library(
    libraryName: Annotated[str, Field(description="Symbol library nickname from sym-lib-table (e.g. Device, project_lib)")],
    projectsDir: Annotated[Optional[str], Field(description="Directory containing project subfolders with .kicad_sch files")] = None,
    schematicPath: Annotated[Optional[str], Field(description="Single .kicad_sch file to update")] = None,
    schematicPaths: Annotated[Optional[List[str]], Field(description="Multiple .kicad_sch files")] = None,
    symbols: Annotated[Optional[List[str]], Field(description="Optional: update only these symbol names (without Library: prefix)")] = None,
    repairMirrorFromBackup: Annotated[bool, Field(description="Restore __m* mirror-cache lib_symbols blocks from backupDir first")] = False,
    backupDir: Annotated[Optional[str], Field(description="Backup folder with matching .kicad_sch filenames (for repairMirrorFromBackup)")] = None,
) -> dict[str, Any]:
    """Refresh embedded lib_symbols cache entries from a KiCad symbol library (equivalent to KiCad's Update Symbol from Library). Skips mirror-cache entries (__m0, __m90, …). Flattens (power) symbols for schematic format. Pass projectsDir to update all schematics in a folder, or schematicPath for one file."""
    return dispatch_command("update_symbol_from_library", {"libraryName": libraryName, "projectsDir": projectsDir, "schematicPath": schematicPath, "schematicPaths": schematicPaths, "symbols": symbols, "repairMirrorFromBackup": repairMirrorFromBackup, "backupDir": backupDir})


_TOOLS = [
    add_library_symbol_property,
    batch_add_and_connect,
    batch_add_components,
    batch_add_no_connects,
    batch_connect,
    batch_edit_schematic_components,
    replace_schematic_component,
    update_symbol_from_library,
]


def register(mcp: Any) -> None:
    for fn in _TOOLS:
        mcp.tool()(fn)
