"""schematic-layout toolset — GENERATED by scripts/gen_toolsets.py, do not hand-edit.

Source of truth: tests/fixtures/tools_baseline.json (module "schematic-layout").
"""

from __future__ import annotations

from typing import Annotated, Any, Dict, List, Literal, Optional, Union

from pydantic import BaseModel, Field

from kicad_mcp.toolsets._common import dispatch_command

class BatchSetSchematicPropertyPositionsUpdatesItem(BaseModel):
    reference: str
    property: Literal["Reference", "Value"]
    x: float
    y: float
    angle: float = 0
    visible: bool = True

def autoplace_schematic_fields(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch file")],
    references: Annotated[Optional[List[str]], Field(description="Only reposition these references (default: all components)")] = None,
    clearance: Annotated[Optional[float], Field(description="Gap in mm between the body/label extent and field text (default one 1.27mm grid unit)")] = None,
) -> dict[str, Any]:
    """Automatically reposition every component's Reference and Value field so they sit outside the component body AND outside any net labels attached to its pins, avoiding collisions with other components and already-placed fields. Like KiCAD's built-in field auto-placement but net-label aware. Optionally limit to specific references."""
    return dispatch_command("autoplace_schematic_fields", {"schematicPath": schematicPath, "references": references, "clearance": clearance})


def batch_set_schematic_property_positions(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch file")],
    updates: Annotated[List[BatchSetSchematicPropertyPositionsUpdatesItem], Field(description="List of field moves to apply")],
) -> dict[str, Any]:
    """Move many Reference/Value field labels in a single file read/write — far faster than repeated set_schematic_property_position calls. Pass an 'updates' array; each item is {reference, property:'Reference'|'Value', x, y, angle?, visible?}. Returns per-item applied/failed lists."""
    return dispatch_command("batch_set_schematic_property_positions", {"schematicPath": schematicPath, "updates": updates})


def set_schematic_property_position(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch file")],
    reference: Annotated[str, Field(description="Component reference designator (e.g., R1, U2)")],
    property: Annotated[Literal["Reference", "Value"], Field(description="Which field to move")],
    x: Annotated[float, Field(description="New X position in mm (absolute schematic coordinate)")],
    y: Annotated[float, Field(description="New Y position in mm (absolute schematic coordinate)")],
    angle: Annotated[float, Field(description="Text angle in degrees (default 0)")] = 0,
    visible: Annotated[bool, Field(description="Whether the field is visible (default true)")] = True,
) -> dict[str, Any]:
    """Move a component's Reference or Value field label to an absolute (x, y) coordinate (mm), optionally rotating or hiding it. Only 'Reference' and 'Value' are supported. Use autoplace_schematic_fields to place all of them automatically."""
    return dispatch_command("set_schematic_property_position", {"schematicPath": schematicPath, "reference": reference, "property": property, "x": x, "y": y, "angle": angle, "visible": visible})


def suggest_schematic_declutter(
    schematicPath: Annotated[str, Field(description="Path to the .kicad_sch file")],
    margin: Annotated[Optional[float], Field(description="Extra clearance in mm when testing label overlap (default 0.3).")] = None,
    references: Annotated[Optional[List[str]], Field(description="Limit which component bodies count as obstacles (default: every component on the sheet).")] = None,
    apply: Annotated[Optional[bool], Field(description="If true, rewrite the label orientations. Default false (dry run \u2014 schematic untouched, proposals only).")] = None,
) -> dict[str, Any]:
    """Re-orient overlapping net/global labels so their text lands in free space and becomes readable. Each label's (at x,y) anchor is its electrical connection point, so it is held FIXED — only the orientation (0/90/180/270) and justification change, throwing the text away from component bodies and other labels. Connectivity is never altered. DRY RUN by default: returns proposals [{name, at, from_angle, to_angle}] plus an overlap score (before/after) WITHOUT modifying the schematic. Set apply=true to rewrite the label orientations. (Phase 1: labels only; symbol spreading + wire reroute is a separate future capability.)"""
    return dispatch_command("suggest_schematic_declutter", {"schematicPath": schematicPath, "margin": margin, "references": references, "apply": apply})


_TOOLS = [
    autoplace_schematic_fields,
    batch_set_schematic_property_positions,
    set_schematic_property_position,
    suggest_schematic_declutter,
]


def register(mcp: Any) -> None:
    for fn in _TOOLS:
        mcp.tool()(fn)
