"""symbol-creator toolset — GENERATED by scripts/gen_toolsets.py, do not hand-edit.

Source of truth: tests/fixtures/tools_baseline.json (module "symbol-creator").
"""

from __future__ import annotations

from typing import Annotated, Any, Dict, List, Literal, Optional, Union

from pydantic import BaseModel, Field

from kicad_mcp.toolsets._common import dispatch_command

class AddSymbolPropertyPosition(BaseModel):
    """Position {x, y} in mm (default: 0, 0)"""

    x: float
    y: float


class CreateSymbolPinsItemAt(BaseModel):
    """Pin endpoint position (where the wire connects)"""

    x: Annotated[float, Field(description="X position in mm")]
    y: Annotated[float, Field(description="Y position in mm")]
    angle: Annotated[float, Field(description="Direction the pin wire extends FROM the symbol body: 0=right, 90=up, 180=left, 270=down")]


class CreateSymbolPinsItem(BaseModel):
    name: Annotated[str, Field(description="Pin name, e.g. 'VCC', 'GND', 'IN+', '~' for unnamed")]
    number: Annotated[Union[str, float], Field(description="Pin number, e.g. '1', '2', 'A1'")]
    type: Annotated[Literal["input", "output", "bidirectional", "tri_state", "passive", "free", "unspecified", "power_in", "power_out", "open_collector", "open_emitter", "no_connect"], Field(description="Electrical pin type")]
    at: Annotated[CreateSymbolPinsItemAt, Field(description="Pin endpoint position (where the wire connects)")]
    length: Annotated[Optional[float], Field(description="Pin length in mm (default 2.54)")] = None
    shape: Annotated[Optional[Literal["line", "inverted", "clock", "inverted_clock", "input_low", "clock_low", "output_low", "falling_edge_clock", "non_logic"]], Field(description="Pin graphic shape (default: line)")] = None


class CreateSymbolRectanglesItem(BaseModel):
    x1: float
    y1: float
    x2: float
    y2: float
    width: Annotated[Optional[float], Field(description="Stroke width in mm (default 0.254)")] = None
    fill: Annotated[Optional[Literal["none", "outline", "background"]], Field(description="Fill type (default: background)")] = None


class CreateSymbolPolylinesItemPointsItem(BaseModel):
    x: float
    y: float


class CreateSymbolPolylinesItem(BaseModel):
    points: Annotated[List[CreateSymbolPolylinesItemPointsItem], Field(description="List of XY points in mm")]
    width: Annotated[Optional[float], Field(description="Stroke width in mm (default 0.254)")] = None
    fill: Optional[Literal["none", "outline", "background"]] = None

def add_symbol_property(
    libraryPath: Annotated[str, Field(description="Path to the .kicad_sym file")],
    symbolName: Annotated[str, Field(description="Symbol name")],
    propertyName: Annotated[str, Field(description="Property name (e.g. Manufacturer, MPN)")],
    propertyValue: Annotated[str, Field(description="Property value")],
    position: Annotated[Optional[AddSymbolPropertyPosition], Field(description="Position {x, y} in mm (default: 0, 0)")] = None,
    hide: Annotated[Optional[bool], Field(description="Hide the property (default false)")] = None,
) -> dict[str, Any]:
    """Add or update a custom property (Manufacturer, MPN, LCSC, etc.) on a symbol in a .kicad_sym library file."""
    return dispatch_command("add_symbol_property", {"libraryPath": libraryPath, "symbolName": symbolName, "propertyName": propertyName, "propertyValue": propertyValue, "position": position, "hide": hide})


def create_symbol(
    libraryPath: Annotated[str, Field(description="Path to the .kicad_sym file (created if missing)")],
    name: Annotated[str, Field(description="Symbol name, e.g. 'TMC2209', 'MyOpAmp'")],
    referencePrefix: Annotated[Optional[str], Field(description="Schematic reference prefix: 'U' (IC), 'R' (resistor), 'J' (connector), etc. Default: 'U'")] = None,
    description: Annotated[Optional[str], Field(description="Human-readable description")] = None,
    keywords: Annotated[Optional[str], Field(description="Space-separated search keywords")] = None,
    datasheet: Annotated[Optional[str], Field(description="Datasheet URL or '~'")] = None,
    footprint: Annotated[Optional[str], Field(description="Default footprint, e.g. 'Package_SO:SOIC-8_3.9x4.9mm_P1.27mm'")] = None,
    inBom: Annotated[Optional[bool], Field(description="Include in BOM (default true)")] = None,
    onBoard: Annotated[Optional[bool], Field(description="Include in netlist for PCB (default true)")] = None,
    pins: Annotated[Optional[List[CreateSymbolPinsItem]], Field(description="List of pins (can be empty for graphical-only symbols)")] = None,
    rectangles: Annotated[Optional[List[CreateSymbolRectanglesItem]], Field(description="Body rectangle(s). Typically one rectangle defining the IC body.")] = None,
    polylines: Annotated[Optional[List[CreateSymbolPolylinesItem]], Field(description="Polyline graphics for custom body shapes (op-amp triangles, etc.)")] = None,
    overwrite: Annotated[Optional[bool], Field(description="Replace existing symbol with same name (default false)")] = None,
) -> dict[str, Any]:
    """Create a new schematic symbol in a .kicad_sym library file (created if missing). After creation, use register_symbol_library so KiCAD finds it. Pin positions are where the wire connects; the symbol body is drawn between them.

Coordinate tips:
- Body rectangle typically spans ±2.54 to ±5.08 mm
- Pins on left side: at.x = body_left - length, angle=0 (wire goes right)
- Pins on right side: at.x = body_right + length, angle=180 (wire goes left)
- Pins on top: at.y = body_top + length, angle=270 (wire goes down)
- Pins on bottom: at.y = body_bottom - length, angle=90 (wire goes up)
- Standard pin length: 2.54 mm, standard grid: 2.54 mm"""
    return dispatch_command("create_symbol", {"libraryPath": libraryPath, "name": name, "referencePrefix": referencePrefix, "description": description, "keywords": keywords, "datasheet": datasheet, "footprint": footprint, "inBom": inBom, "onBoard": onBoard, "pins": pins, "rectangles": rectangles, "polylines": polylines, "overwrite": overwrite})


def delete_symbol(
    libraryPath: Annotated[str, Field(description="Path to the .kicad_sym file")],
    name: Annotated[str, Field(description="Symbol name to delete")],
) -> dict[str, Any]:
    """Remove a symbol from a .kicad_sym library file."""
    return dispatch_command("delete_symbol", {"libraryPath": libraryPath, "name": name})


def list_symbols_in_library(
    libraryPath: Annotated[str, Field(description="Path to the .kicad_sym file")],
) -> dict[str, Any]:
    """List all symbol names in a .kicad_sym library file."""
    return dispatch_command("list_symbols_in_library", {"libraryPath": libraryPath})


def register_symbol_library(
    libraryPath: Annotated[str, Field(description="Full path to the .kicad_sym file")],
    libraryName: Annotated[Optional[str], Field(description="Nickname (default: file name without extension)")] = None,
    description: Optional[str] = None,
    scope: Annotated[Optional[Literal["project", "global"]], Field(description="project = writes sym-lib-table next to .kicad_pro; global = user config")] = None,
    projectPath: Annotated[Optional[str], Field(description="Path to .kicad_pro or its directory (for scope=project)")] = None,
) -> dict[str, Any]:
    """Register a .kicad_sym library in KiCAD's sym-lib-table so symbols can be used in schematics. Run this after create_symbol when KiCAD shows 'library not found'."""
    return dispatch_command("register_symbol_library", {"libraryPath": libraryPath, "libraryName": libraryName, "description": description, "scope": scope, "projectPath": projectPath})


_TOOLS = [
    add_symbol_property,
    create_symbol,
    delete_symbol,
    list_symbols_in_library,
    register_symbol_library,
]


def register(mcp: Any) -> None:
    for fn in _TOOLS:
        mcp.tool()(fn)
