"""ui toolset — GENERATED by scripts/gen_toolsets.py, do not hand-edit.

Source of truth: tests/fixtures/tools_baseline.json (module "ui").
"""

from __future__ import annotations

from typing import Annotated, Any, Dict, List, Literal, Optional, Union

from pydantic import BaseModel, Field

from kicad_mcp.toolsets._common import dispatch_command

def check_kicad_ui() -> dict[str, Any]:
    """Check if KiCAD UI is currently running"""
    return dispatch_command("check_kicad_ui", {})


def get_backend_state() -> dict[str, Any]:
    """Return the active backend, realtime status, loaded project/board paths, and dirty state."""
    return dispatch_command("get_backend_state", {})


def launch_kicad_ui(
    projectPath: Annotated[Optional[str], Field(description="Optional path to .kicad_pcb file to open")] = None,
    autoLaunch: Annotated[Optional[bool], Field(description="Whether to launch KiCAD if not running (default: true)")] = None,
) -> dict[str, Any]:
    """Launch KiCAD UI, optionally with a project file"""
    return dispatch_command("launch_kicad_ui", {"projectPath": projectPath, "autoLaunch": autoLaunch})


_TOOLS = [
    check_kicad_ui,
    get_backend_state,
    launch_kicad_ui,
]


def register(mcp: Any) -> None:
    for fn in _TOOLS:
        mcp.tool()(fn)
